### ISSUE TITLE
error importing in svelte project

### ISSUE THREAD

**Issue by shedali** [IBM/carbon-components-svelte#102]
just trying out library for first time in a svelte project

```
 ENOENT: no such file or directory, open 'node_modules/carbon-components-svelte/src/index.js'
```

I believe the package.json svelte property references src/index.js which is not published to npm

**Comment by metonym** [comment]
Hi @shedali , thank you for opening this issue. We published an initial version but are still working on a full v1.0 release (almost there).

In the meanwhile, I will release an updated version with documentation.

**Comment by metonym** [comment]
@shedali A new version (v0.2.1) is published.

Here is a CodeSandbox demo: https://codesandbox.io/s/carbon-components-svelte021-lhvc4

**Comment by shedali** [comment]
thanks @metonym
