### ISSUE TITLE
DatePicker broken?

### ISSUE THREAD

**Issue by drop1down** [IBM/carbon-components-svelte#130]
I just tested carbon with few components.
I got it running (Buttons, Dropdown)

But DatePicker was added by svelte as empty `<div>` - i do not see ui

I used simple `<DatePicker />` as code with import for this.

bug?

**Comment by metonym** [comment]
Thanks for raising this bug.

In CodeSandbox, the `DatePicker` for type "single" or "range" is throwing an error. Strangely, the [Storybook works](http://localhost:9090/?path=/story/datepicker--single).

**Comment by metonym** [comment]
After some more debugging, I'm having trouble reproducing the error outside of CodeSandbox. However, I believe the error results from `base` (first parameter of `flatpickr`) being read as "null."

The `DatePicker` component works fine in:

- Storybook
- Non-CodeSandbox Webpack set-up

Furthermore, I've isolated the `DatePicker` component in CodeSandbox, and it is working fine: https://codesandbox.io/s/datepicker-xcuo6

@drop1down Could you provide more info on your set-up? Were you just using the CodeSandbox linked in the README?

**Comment by drop1down** [comment]
i used fresh template from here:
https://github.com/sveltejs/template/archive/master.zip

add carbon-components-svelte to package.json
npm install

replace App.svelte with this:

```
<script>
	import { Datepicker } from 'carbon-components-svelte';
</script>

<main>
	<DatePicker />
</main>
```

npm run dev

this is my result in any browser / win 10:

`<div class="bx--form-item"><div class="bx--date-picker bx--date-picker--simple" id="0.6775614213691941"></div></div>
`

**Comment by drop1down** [comment]
Sorry, i added your example to my code and this works:

```
<script>
 import { DatePicker,DatePickerInput}  from "carbon-components-svelte";

 let value = "";
</script>

<svelte:head>
  <link
    rel="stylesheet"
    href="https://unpkg.com/carbon-components@10.9.0/css/carbon-components.min.css" />
</svelte:head>

<DatePicker
  id="date-picker"
  bind:value
  datePickerType="single"
  on:change={({ detail }) => {
    console.log('change', detail);
  }}>
  <DatePickerInput id="date-picker-input"
    placeholder='mm/dd/yyyy'
    on:close={() => {
      console.log('on:close');
    }}
    on:input={() => {
      console.log('on:input');
    }} />
</DatePicker>
```

Is this correct way how to use it?
I thought at first <DatePicker /> was enough

**Comment by metonym** [comment]
@drop1down Yes, that's the correct way to use it. The Storybook story source code is in same folder as the component; it's a bit hidden right now.

We're rewriting the documentation from scratch where the code usage is as the forefront (#100).
