### ISSUE TITLE
UIShellSideNav bug

### ISSUE THREAD

**Issue by mfeitoza** [IBM/carbon-components-svelte#138]
Hi!

when Shell Side Nav have two itens with same name both show as active:

![Opera Snapshot_2020-02-12_205503_localhost](https://user-images.githubusercontent.com/8423813/74388438-2cea8e00-4dda-11ea-9c1d-efe58712ee00.png)

And any plans to make a UIShell compoments based too?

**Comment by metonym** [comment]
@mfeitoza Thank you for raising this issue.

For your second point, I think it would be good to make the UIShell component-based for consistency with the rest of the library. However, this may be a post-1.0 release

**Comment by mfeitoza** [comment]
Thank you @metonym for you reply!

I will be a active user/contributor because I started to use in an client web app (is not in production)! So I will work in an component based Side Nav this week.
