### ISSUE TITLE
Theme support

### ISSUE THREAD

**Issue by NickStarlight** [IBM/carbon-components-svelte#167]
How do we apply themes as described [here](https://www.carbondesignsystem.com/guidelines/themes/)?

Using:
```
<style type="text/sass" global>
@import "node_modules/carbon-components/scss/globals/scss/vendor/@carbon/themes/scss/themes";

$carbon--theme: $carbon--theme--g100;
@include carbon--theme();

@import 'node_modules/carbon-components/scss/globals/scss/styles';
</style>
```

Seems to have no effect at all.

**Comment by NickStarlight** [comment]
Nevermind, this DOES work, it was a problem on how i was handling my rollup.
The snippet bellow works like charm if you wan't use the Gray-100 theme:

```
@import "carbon-components/scss/globals/scss/vendor/@carbon/themes/scss/themes";

$carbon--theme: $carbon--theme--g100;
@include carbon--theme();

@import 'carbon-components/scss/globals/scss/styles';
```

**Comment by arcfide** [comment]
@NickStarlight I'm having this same issue, but it's not clear what I need to do in my rollup to fix this. Do you have any information on how to do this?

**Comment by arcfide** [comment]
Aha! I see that the path you used is different than the path recommended on the main documentation. Adjusting the path fixes things.
