### ISSUE TITLE
Composed DataTable

### ISSUE THREAD

**Issue by mfeitoza** [IBM/carbon-components-svelte#171]
At moment only DataTable is exported, but there an example of composed DataTable in story file? Is finished?

**Comment by metonym** [comment]
It's a WIP:

This [https://github.com/IBM/carbon-components-svelte/blob/master/src/components/DataTable/DataTable.Story.svelte](story) contains an example for a sortable/readonly composed DataTable.

**Comment by mfeitoza** [comment]
I tested and works fine, what is missing to finish?
