### ISSUE TITLE
Appropriate way to ensure Grid shows up below Header

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#175]
When using a Header, followed by a Grid as in the following, the content of the Grid may hid underneath the Header, what's the appropriate way to deal with this?

```
<Header company="something" platformName="Something else"></Header>
<div class="bx--grid">
....
</div>
```

**Comment by metonym** [comment]
Hi @arcfide , the `Header` component has a fixed position, which can obscure content directly below it.

Try increasing the `margin-top` value for `bx--grid`:

```html
<script>
  import { Header } from "carbon-components-svelte";
</script>

<svelte:head>
  <link
    rel="stylesheet"
    href="https://unpkg.com/carbon-components@10.9.0/css/carbon-components.min.css"
  />
</svelte:head>

<style>
  .bx--grid {
    margin-top: 3rem;
  }
</style>

<Header company="something" platformName="Something else"></Header>
<div class="bx--grid">....</div>
```

**Comment by arcfide** [comment]
Due to some SASS stuff that I have, I was unable to do this exactly, but I was able to use the principle to work around the issue. Thanks.
