### ISSUE TITLE
Clean way to use Grid with Sapper?

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#176]
Is there a clean way to use the Grid with Sapper? It appears that I need to use Sass, but is there a way to avoid using Sass and just use Sapper for this?

**Comment by metonym** [comment]
Hi @arcfide 

Grid-related styles are shipped with the [pre-compiled CSS for Carbon](https://unpkg.com/carbon-components@10.9.3/css/carbon-components.min.css). Then, in your Svelte code, you should be able to work with grid selectors like such:

```html
<svelte:head>
  <link
    rel="stylesheet"
    href="https://unpkg.com/carbon-components@10.9.0/css/carbon-components.min.css"
  />
</svelte:head>

<div class="bx--grid">
  <div class="bx--row">
    <div class="bx--col bx--no-gutter">
      <div class="outside">
        <div class="inside">1</div>
      </div>
    </div>
    <div class="bx--col bx--no-gutter">
      <div class="outside">
        <div class="inside">1</div>
      </div>
    </div>
    <div class="bx--col bx--no-gutter">
      <div class="outside">
        <div class="inside">1</div>
      </div>
    </div>
    <div class="bx--col bx--no-gutter">
      <div class="outside">
        <div class="inside">1</div>
      </div>
    </div>
  </div>
</div>
```

Personally, I haven't yet used SCSS with Sapper, but it should be possible by customizing the default template build set-up (for either Webpack or Rollup).

However, if you're referring to a `Grid` component, that is not yet supported by this library. We are currently aligning with `carbon-components` minor version 10.9.x.

**Comment by arcfide** [comment]
I was speaking about the Grid-related styles you mention above, but they default to the 12-column grid rather than the new 16-column grid that is mentioned in the latest documentation. It appears that you need to use Sass to optionally enable the 16-column grid. I have been able to do this using the following guide, but was hoping to find another way that didn't involve Sass.

https://medium.com/@sean_27490/svelte-sapper-with-sass-271fff662da9
