### ISSUE TITLE
Button with icon and Text Displays iconDescription

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#177]
The iconDescription as far as I can tell should not be displayed when a button has text and an icon.

**Comment by metonym** [comment]
Could you provide an example?

```html
<Button icon={Add16} iconDescription="Button with icon">
  Button with icon
</Button>
```

The `iconDescription` is used as the value for `aria-label` passed to the Add16 svg element.

**Comment by arcfide** [comment]
These buttons result in a strange hover text when I mouse over them that is very distracting:

```
      <Button kind="secondary" icon={Add16} 
              iconDescription="Add a new table">Table</Button>
      <Button kind="primary" icon={Add16} 
              iconDescription="Create a tournament">Tournament</Button>
```

**Comment by arcfide** [comment]
If there is no `iconDescription` provided, the hover text shows as 'undefined'.

**Comment by arcfide** [comment]
Ah, when I upgraded to 0.6.0 this appears to be fixed.
