### ISSUE TITLE
ghost icon only buttons in the Header Panels, coloring?

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#182]
What's the best way to color a small ghost icon-only button in a Header Utilities panel? Right now the icons show by default in the dark text color, meaning that they are hidden in the panel.

**Comment by metonym** [comment]
I would recommend `:global()` modifier for this use case that targets SVG elements with a "data-carbon-icon" data selector. This way, a custom fill color will not affect non-Carbon SVG elements.

```html
<script>
  import Add16 from 'carbon-icons-svelte/lib/Add16';
</script>

<style>
  :global(svg[data-carbon-icon]) {
    fill: blue;
  }
</style>

<Add16 />
```

[**Svelte REPL**](https://svelte.dev/repl/8c9421aafc484a7d8fd05b253d1d9848?version=3.16.7)

<img width="836" alt="Screen Shot 2020-05-09 at 5 44 50 PM" src="https://user-images.githubusercontent.com/10718366/81488406-3b034b80-921d-11ea-8e51-95035dd81d3d.png">

Note: You may need increase the specificity if you just want to target icons in the Header Utilities panel:

```html
<style>
:global(.${header-panel-common-ancestor} svg[data-carbon-icon]) {
    fill: blue;
}
</style>
```

This is one of the reasons why [carbon-icons-svelte](https://github.com/IBM/carbon-icons-svelte#data-carbon-icon-selector) ships with a `[data-carbon-icon]` utility selector.

**Comment by arcfide** [comment]
Thanks for this! I was able to get this working.
