### ISSUE TITLE
ContentSwitcher with Icons

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#183]
It would be nice to be able to use icons as the contents for content switchers.

**Comment by metonym** [comment]
Agreed. Would you be interested in submitting a PR?

**Comment by arcfide** [comment]
It will depend on whether we decide to go this route in our own project. If so, then I will submit a PR on the feature, if you don't get to it first.

**Comment by metonym** [comment]
This feature has been added in v0.8.0.

A `slot` wraps the `text` prop in the Content Switcher `Switch` component.

In this reduced example, the first two switches use the `text` prop while the third switch overrides it with an icon.

```html
<ContentSwitcher>
  <Switch text="First section" />
  <Switch text="Second section" />
  <Switch>
    <span style="display: flex; align-items: center;">
      <Add16 style="margin-right: .25rem;" />
      Third section
    </span>
  </Switch>
</ContentSwitcher>
```

<img width="1127" alt="Screen Shot 2020-07-19 at 12 37 16 PM" src="https://user-images.githubusercontent.com/10718366/87883549-064e0600-c9bd-11ea-8a85-05a643a206cd.png">

**Comment by arcfide** [comment]
Very cool!
