### ISSUE TITLE
Add header key and sort direction to the TableHeader on:click event in the DataTable component

### ISSUE THREAD

**Issue by mabentley85** [IBM/carbon-components-svelte#186]
I think it's important that the Header Key and Sort direction are included in the `click:header` dispatch event.

I would think that in most cases changing the column that a table is sorted by or the sort direction would necessitate an API request.  Also the ability to disable the current behavior of sorting only the rows currently in the DataTable would need to be added.

Do any plans exist to enable this? If not I can volunteer to add this functionality.

**Comment by metonym** [comment]
This would be a nice enhancement, looking forward to the PR.

**Comment by mabentley85** [comment]
Pull Request #188

**Comment by metonym** [comment]
Released in v0.7.2 – [changelog notes](https://github.com/IBM/carbon-components-svelte/blob/master/CHANGELOG.md#072---2020-06-04)
