### ISSUE TITLE
Prevent sortable DataTable sorting when a Header is clicked

### ISSUE THREAD

**Issue by mabentley85** [IBM/carbon-components-svelte#189]
When a sortable DataTable's header is clicked the current behavior is to sort the table's current rows accordingly.

In cases where developers would like to trigger an API call to repopulate the table entirely based on the column and direction being sorted by, sorting of the current rows of the table is not desirable.

Any thoughts on how this should be handled?

My suggestion is to add a boolean component property (maybe call it `sortLocalData` or something like that) to determine whether or not the current sorting behavior is triggered when a sortable DataTable header is clicked.

**Comment by metonym** [comment]
Can the behavior that you describe be controlled by the existing API?

For your use case, would it be sufficient to temporarily disable `sortable` when triggering the API call?

**Comment by mabentley85** [comment]
Hadn't thought about toggling the `sortable` property.  I gave it a try, and it does work, but there is a flicker when the table goes from the sortable to non-sortable state and back (mainly the column widths shifting around).

So a more elegant solution would be nice.

**Comment by Yiin** [comment]
Fixed it by passing custom sort function to each header

```ts
export const nosort = () => 0 as const;
```

```js
headers={[
  { key: 'id', value: 'ID', sort: nosort },
  { key: 'gameType', value: 'Game type', sort: nosort },
]}
```

and handling sort manually thought `on:click:header`:

```js
<DataTable
  sortable
  on:click:header={handleDataTableSort}
```
```js
function handleDataTableSort({ detail }) {
  orderBy(
    detail.header.key,
    { ascending: 'ASC', descending: 'DESC' }[detail.sortDirection],
  )();
}
  ```
