### ISSUE TITLE
Can a Modal be created without the close Icon?

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#194]
For cases where the Modal requires an input before any progress can be made, is where a way to disable or remove the close icon?

**Comment by metonym** [comment]
Currently, no. The purpose of the close button in a [modal (and its passive variant) ](https://www.carbondesignsystem.com/components/modal/usage) is to allow a means for the user to escape the modal.

For your use case, would disabling the primary button in the modal be acceptable?

**Comment by arcfide** [comment]
Not for the use case I'm thinking about. I'm thinking about the case where another action has been "triggered" by something else in the system that halts all further progress in the application until the user responds with either an affirmation or a negation of the state. The transactional modal paradigm seems ideal in this situation because it represents a very strong, significant "break" from the flow of the rest of the application, and choosing an accept/primary response means that the application completely deviates in behavior after that, whereas a reject returns the application to the original state. However, the user *must* reject or accept, and cannot simply progress without doing so, thus making the close option not helpful, because I would just need to reopen the dialog, as no other action is posslble. 

I thought about making the close button an implicit reject, but that seems unintuitive and likely to result in some problems.

**Comment by metonym** [comment]
Interesting use case.

Consider raising this issue in the [Carbon monorepo](https://github.com/carbon-design-system/carbon/issues) because it pertains to the design of the component.

**Comment by arcfide** [comment]
Sounds like a plan. I've been able to "workaround" this issue by simply always forcing a reopen when someone closes the dialog, but I would be interested in a better solution.

On June 29, 2020 at 22:46 GMT, Eric Liu <notifications@github.com> wrote:

Interesting use case.

Consider raising this issue in the [Carbon monorepo](https://github.com/carbon-design-system/carbon/issues) because it pertains to the design of the component.
