### ISSUE TITLE
Add ability to bind html input element with a variable

### ISSUE THREAD

**Issue by gufoscuro** [IBM/carbon-components-svelte#196]
Hello!
Would it make sense to add the ability to bind the input element with a variable which can be passed to the wrapper?
something like:

`<TextInput bind:value={inputValue} bind:htmlInput={inputField} />`

so you could do things like

`inputField.focus()`

I know that refs suck, but unfortunately sometimes you are forced to do something imperatively...

Thanks!

**Comment by metonym** [comment]
@gufoscuro Great suggestion! I've experienced the same pain point.

I assume that you are currently using the following workaround:

```html
<script>
  import { onMount } from "svelte";

  let value = "";

  onMount(() => {
    const textInputRef = document.getElementById("input");

    if (textInputRef != null) {
      textInputRef.focus();
    }
  });
</script>

<TextInput id="input" bind:value />
```

**Comment by gufoscuro** [comment]
Exactly!
But as you would agree, that workaround is anything but comfortable – a ref or at least an autofocus prop would be great (I'd go with the ref btw ;)

**Comment by metonym** [comment]
This feature has been added in v0.8.0.

Certain "interactive" components (e.g. text input, text area, anchor links) now bind a `ref` prop as a reference.

**[Example in the Svelte REPL](https://svelte.dev/repl/97a9bcacffea426eab873c90be0f8860?version=3.24.0)**

```html
<script>
  import { onMount } from "svelte";
  import { TextInput } from "carbon-components-svelte";

  let ref;

  onMount(() => {
    ref.focus();
  })
</script>

<TextInput bind:ref />
```
