### ISSUE TITLE
Modal dialog is incompatible with Sapper SSR

### ISSUE THREAD

**Issue by arcfide** [IBM/carbon-components-svelte#200]
When using SSR, the Modal component doesn't work because it has afterUpdate and onDestroy hooks that reference `document` leading to SSR errors in Sapper. 

https://github.com/IBM/carbon-components-svelte/blob/64e914ff8c6556cb12ec29401ddddbd8a342011e/src/components/Modal/Modal.svelte#L41

**Comment by metonym** [comment]
Fixed and released in version 0.8.1
