### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by pjriot** [IBM/carbon-components-svelte#214]
With the newly announced svelte typescript support for svelte, I was wondering if there were plans to publish types for this project?

**Comment by metonym** [comment]
It's seriously worth considering. The Svelte team did an incredible job with adding first class TypeScript support.

**Comment by metonym** [comment]
TypeScript definitions have been added to the sibling package [carbon-icons-svelte](https://github.com/IBM/carbon-icons-svelte/pull/76). The definitions stub the props interface for the Icon components.

With VSCode + Svelte VSCode extensions, I'm experiencing:

- Module import autocomplete
- Typeahead info for component props

**Comment by metonym** [comment]
@pjriot TypeScript definitions are published in version >=0.9.0.

In VSCode along with the official Svelte VSCode extension, I experience:

## Type checking for component props 

<img width="496" alt="Screen Shot 2020-07-30 at 6 42 36 PM" src="https://user-images.githubusercontent.com/10718366/88991247-0be8fd00-d295-11ea-8d3e-c51d71f6b20f.png">


<img width="762" alt="Screen Shot 2020-07-30 at 6 43 02 PM" src="https://user-images.githubusercontent.com/10718366/88991217-f1af1f00-d294-11ea-806d-4b1317e432fd.png">


## Module import auto-complete

<img width="524" alt="Screen Shot 2020-07-30 at 6 43 21 PM" src="https://user-images.githubusercontent.com/10718366/88991242-025f9500-d295-11ea-9c0b-ea294e3187f6.png">

**Comment by pjriot** [comment]
Thats incredible. I was looking at react / ant and ts, now it looks like I have another stack to evaluate! Than you for the extremely quick turnaround!
