### ISSUE TITLE
ComboBox Dispatch when value is changed

### ISSUE THREAD

**Issue by mabentley85** [IBM/carbon-components-svelte#223]
Sorry if there is already a good way to handle when an option is selected or cleared in a ComboBox, but it's not jumping out at me.

Could this be better handled by adding a dispatch when the value has changed? Similar to how the the DatePicker works.

I am building a table with a dynamic amount of filters and would like to know which combobox values have changed.

**Comment by metonym** [comment]
@mabentley85 "select" and "clear" events are dispatched by the ComboBox – released in 0.9.0.

In the [ComboBox Story](https://ibm.github.io/carbon-components-svelte/?path=/story/combobox--default), you can see the "select" and "clear" events logged to the browser console.

**Comment by mabentley85** [comment]
@metonym Awesome! Thank you so much for the quick response
