### ISSUE TITLE
ESlint A11y errors within package

### ISSUE THREAD

**Issue by ljamzin** [IBM/carbon-components-svelte#226]
Hi. When I degit the sapper template, add carbon-components-svelte to it and try including the navbar component and building, I get the following warning for multiple components:

(...)\node_modules\carbon-components-svelte\src\StructuredList\StructuredListRow.svelte
A11y: A form label must be associated with a control.
20:
21: {#if label}
22:   <label
      ^
23:     role="presentation"
24:     {tabindex}

Is this a false alarm or an issue with your package?
Thanks

**Comment by metonym** [comment]
It seems that the "a11y-label-has-associated-control" is a new warning add in [Svelte v3.24.1](https://github.com/sveltejs/svelte/blob/master/CHANGELOG.md#3241).

In this case, it's a false positive – will disable the warning in the next release.

**Comment by ljamzin** [comment]
Small correction, I got 6 warnings but the issue is present in only 2 components:
Loading.svelte
StructuredListRow.svelte

**Comment by metonym** [comment]
This is fixed in [v0.9.4](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.9.4)
