### ISSUE TITLE
Svelte Ts support: SelectItem in `index.d.ts` has no props defined.

### ISSUE THREAD

**Issue by Robbie-Cook** [IBM/carbon-components-svelte#227]
The `SelectItem` component has no props defined in index.d.ts: https://github.com/IBM/carbon-components-svelte/blob/ba2e77eb477d0d705405612fd72544d2a0282d92/types/index.d.ts#L970

But has props where `SelectItem` is defined: https://github.com/IBM/carbon-components-svelte/blob/ba2e77eb477d0d705405612fd72544d2a0282d92/src/Select/SelectItem.svelte#L2

This is more obvious in when you call the props, e.g. in https://github.com/IBM/carbon-components-svelte/blob/ba2e77eb477d0d705405612fd72544d2a0282d92/src/Select/Select.Story.svelte#L24

When using Ts with Svelte, there is an error because the props are not properly defined.

**Comment by metonym** [comment]
Thanks for catching this – I'm currently rehauling the process of generating documentation and TS definitions.

**Comment by Robbie-Cook** [comment]
Great! Thanks!

**Comment by metonym** [comment]
@Robbie-Cook TypeScript definitions are updated in [v0.9.6](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.9.6).

Types for `SelectItem`: [types/index.d.ts#L3406](https://github.com/IBM/carbon-components-svelte/blob/master/types/index.d.ts#L3406)

**Comment by Robbie-Cook** [comment]
Nice! Thanks!
