### ISSUE TITLE
DatePicker not working in last version

### ISSUE THREAD

**Issue by CodingWill0** [IBM/carbon-components-svelte#232]
Tried to make it run (REPL, Sandbox, local machine). It doesn't work.
I manually created the cx.js (not in the last version), from https://codesandbox.io/s/datepicker-xcuo6?file=/App.svelte:310-673 (old version).
And it worked perfectly.
If you need any extra proof, I can attach screenshots or whatever. But I think you can see it by yourself just testing.
![image](https://user-images.githubusercontent.com/38038438/90160648-5d63b280-dd92-11ea-8982-5dc86d9d365a.png)

flatpickr$1 is not a constructor

Cheers.

**Comment by metonym** [comment]
@CodingWill0 Thank you for raising this critical issue. Fixed in [v0.9.6](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.9.6)

**Comment by albertms10** [comment]
As this issue is formally resolved, may it be closed?
