### ISSUE TITLE
DatePicker - cannot obtain date range through value

### ISSUE THREAD

**Issue by therealpaulgg** [IBM/carbon-components-svelte#234]
Unlike the React carbon design components, which the value can be one of the following:
```
string | string | number | object[] | object | number
```

In the svelte version, only a string is allowed. This means that when trying to obtain a value, one can only get it through the event. This seems counterintuitive to the Svelte framework.

Would it be possible to add both string and [string, string] as types for the date picker, or even Date objects?

Or if there's something I'm missing here, please let me know.

**Comment by metonym** [comment]
@therealpaulgg You're correct. The selected date values are only obtainable from the `on:change` event. Although the dispatched event formats support both "mm/dd/yyyy" as well as the native Date constructor, there is no two-way binding for the start/end values. I agree that this is counterintuitive to Svelte. 

This is a limitation of the current implementation of the range DatePicker and should be addressed.

I like your suggestion of a [string, string] format. A new prop called "rangeValue" specifically for the range DatePicker could accept an optional value of `[string, string]` to initialize and bind the range.

**Comment by metonym** [comment]
Supported in v0.40.0

For a [range DatePicker](https://carbon-svelte.vercel.app/components/DatePicker#range), bind to `valueFrom` and `valueTo`.
