### ISSUE TITLE
TextInput - Auto validate attribute is not working in Form component.

### ISSUE THREAD

**Issue by kamil-murtaza** [IBM/carbon-components-svelte#238]
## Description
Auto validate attribute is not working in TextInput component.

## Expected Outcome
When value of the field is empty/invalid and I enter a valid value it should auto validate the text field.

## Actual Outcome
When I enter a valid value in the field it does not auto validate , I have to validate it myself by calling it with submit form.

Im happy to submit a PR.

**Comment by metonym** [comment]
Can you provide an example?

**Comment by kamil-murtaza** [comment]
Yes for example there are business cases in which we want to validate a field as the user types without submitting the form i.e. it should auto validate the field on value change function .

e.g In an email field, if I enter an invalid email it should notify me without submitting the form that its an invalid value , and after correcting the value it should remove the error without submitting the form.

For that we'll have to do the following changes (Pseudo Code) : 

> $ onValueChange(value);
> 
> function onValueChange(value) {
>     if (autoValidate === true ) {
>        validateInputComponent();
> }
> 
> function validateInputComponent(){
>     getInputComponent.checkValidity();
> }

Its also done in paper-input fields of Polymer. You can also see it here.

https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.js#L151.

**Comment by metonym** [comment]
So essentially you want to display is an input is invalid given a certain condition? Each input component has an `invalid` prop to allow you to indicate an error in a declarative manner.

So for your example:

```html
<script>
  let submitted = false;
</script>

<TextInput invalid={submitted && value.length < 1} bind:value />
```

**Comment by kamil-murtaza** [comment]
Ok I will try it using the invalid prop. 
Thank you.

**Comment by kamil-murtaza** [comment]
Its working now in this way.
Thank you.
