### ISSUE TITLE
Understanding Header

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#245]
With the Header component, there is a prop: `isSideNavOpen`. If you set this to false, and wanted to persist a hamburger (to the far left before site title) to open it, even on desktop - is this possible? How do you structure the UI Shell components?

What is the intended usage for that prop?

Cheers!

**Comment by ispyinternet** [comment]
Ok, great thanks for the explanation. BTW, got some funky behaviour if you click on the last 3 actions in the nav, they are not 'keeping up', so third click produces second click behaviour...

https://r2.cron.tv/

**Comment by metonym** [comment]
Thanks for the tip. I'll need to investigate the scenario of using multiple header panels.

**Comment by ispyinternet** [comment]
* deleted my post to remove our dev url *

**Comment by ispyinternet** [comment]
Actually just following up, I remember why I asked this in the first place, if I place a content after the header:

```
...
     </SideNav>
</Header>
<Content><slot></slot></Content>
```

The left side of the content is covered by the nav, when it is open on desktop.

If I pull `<SideNav>` outside of header, the content flows to the right of the sidenav, but when sidenav is collapsed on mobile, I see a left gutter caused by:

```
.bx--side-nav ~ .bx--content {
    margin-left: 3rem;
}
```

**Comment by metonym** [comment]
@ispyinternet for that use case, I would recommend:

- put `SideNav` within `Header`
- use the `Grid` components as a child of `Content` and add an offset to the columns

The offset for columns can be controlled per breakpoint (i.e. `xlg`, `lg`, `md`, `sm`). This may need some experimenting with to get right.

In the following example, in the `xlg` desktop breakpoint, the Column will have a left offset of `3`. When the `md` breakpoint is triggered, the offset is removed.

```html
<Header>
  ...
  <SideNav>...</SideNav>
</Header>

<Content>
  <Grid>
    <Row>
      <Column xlg={{ span: 8, offset: 3 }}  md={{ span: 8, offset: 0 }}>
         Hello
      </Column>
    </Row>
  </Grid>
</Content>
```

**Comment by ispyinternet** [comment]
Ok, is this WIP? Seems like a standard layout scenario that you shouldn't have to hack into place. 

Cheers!

**Comment by metonym** [comment]
Nice – especially for the Carbon theme sites they use a lot of custom CSS.

**Comment by ispyinternet** [comment]
Still find it odd that the sidebar / content area are not handled fluidly on mobile / desktop -  but anyway I guess that's not really your concern with this library - one for the carbon core.🤷 Thanks!
