### ISSUE TITLE
Missing ESM support in flatpickr inhibits use with ESM development approaches

### ISSUE THREAD

**Issue by metonym** [IBM/carbon-components-svelte#249]
The flatpickr PR to support ESM was just merged: https://github.com/flatpickr/flatpickr/pull/2046#event-3763594915

@metonym upgrade `flatpickr` when ESM imports is released

---

**Context**

Currently, `flatpickr` does not support ESM. `carbon-components-svelte` relies on `flatpickr` for the `DatePicker` component.

As a result, it is not possible to use base imports when using `carbon-components-svelte` with "no bundle" development tools like svite, snowpack or es-dev-server.

For example, the following code throws an error when using svite/snowpack:

```js
import { Button } from "carbon-components-svelte";
```

**Workarounds:**

1) Direct import

```js
import { Button } from "carbon-components-svelte/src/Button";
```

2) Add `flatpickr` to optimizable dependencies in `vite.config.js`

```js
module.exports = {
  optimizeDeps: {
    include: [
      "flatpickr",
      "flatpickr/dist/l10n/index.js",
      "flatpickr/dist/plugins/rangePlugin",
    ],
  },
};
```

**Comment by nestarz** [comment]
I also can't use carbon using vite/svite, but I get a lot of errors using the workaround that I fixed by adding this to optimizeDeps:
```
      "lodash.isequal",
      "lodash.omit",
      "lodash.findlast",
      "warning",
      "window-or-global",
      "invariant"
```
Also I needed to install prop-types as dep.

I am really interested with the upgrade of flat-pickers to remove those !

**Comment by metonym** [comment]
@nestarz what Carbon package(s) are you using?

For Svelte, we don't require `carbon-components`.

**Comment by nestarz** [comment]
I am using React and those components:
```
import DataTable, {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableHeader,
  TableRow,
} from "carbon-components-react/es/components/DataTable";
import {
  PageSelector,
  Pagination,
} from "carbon-components-react/es/components/Pagination/experimental";
```

I replied to this thread because its a similar issue in carbon-components-react

**Comment by metonym** [comment]
@nestarz Even when flatpickr supports ESM, I think you'll still need to include the dependencies you listed in the optimizableDeps.

**Comment by nestarz** [comment]
> @nestarz Even when flatpickr supports ESM, I think you'll still need to include the dependencies you listed in the optimizableDeps.

Not sure why but I keep that in mind, thanks !

**Comment by metonym** [comment]
```
      "lodash.isequal",
      "lodash.omit",
      "lodash.findlast",
      "warning",
      "window-or-global",
      "invariant"
```

These are deps required by `carbon-components-react`, not flatpickr. AFAIK, flatpickr contains zero dependencies.
