### ISSUE TITLE
Dropdown menu icon does not toggle open/close on click

### ISSUE THREAD

**Issue by albertms10** [IBM/carbon-components-svelte#251]
When clicking a `Dropdown` menu icon (chevron), it is supposed to toggle the opened/closed state of the menu. Instead, only works clicking on the component area besides it.

[Example from Storybook](https://ibm.github.io/carbon-components-svelte/?path=/story/dropdown--default)

By the way, it does work in similar components like `ComboBox` or `Select`.

**Comment by metonym** [comment]
@albertms10 Nice catch.

Patched in version 0.12.2
