### ISSUE TITLE
How to use data-modal-primary-focus

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#257]
I have a form in a modal. I'm trying to get the first input to focus on open by:

```
 <TextInput bind:value="{name}" data-modal-primary-focus></TextInput>
```

I can see the data attribute on the  wrapping `div` - but obviously it's not achieving what I am looking for. 

Am I doing it correctly or is it a possible bug?

Cheers!

**Comment by metonym** [comment]
To focus an element when opening a modal, specify the selector using the `Modal` prop `selectorPrimaryFocus`.

In the reduced example, the password input element will be focused when opening the modal:

```html
<Modal selectorPrimaryFocus="#focus-me-when-the-modal-opens">
  <PasswordInput id="focus-me-when-the-modal-opens" />
</Modal>
```

The issue that you're running into is that currently, many components don't forward `$$restProps` to the input element (e.g. `TextInput`, `PasswordInput`).

This is why "data-modal-primary-focus" is being sent to the `div` element. You'll need to use the `id` prop.

**Comment by ispyinternet** [comment]
Gotcha, thanks!
