### ISSUE TITLE
Add custom DataTable sorting method

### ISSUE THREAD

**Issue by albertms10** [IBM/carbon-components-svelte#282]
The current DataTable sorting just works fine. It would also be great to be able to set a custom sorting method to manage situations where the displayed data is treated differently than the ‘raw’ data, e.g. currency, should be sorted as a number (`3217.58`) and displayed as a formatted string (`$3,217.58`).

**Comment by metonym** [comment]
Agreed. Maybe by exporting the default sort function as a prop?

**Comment by albertms10** [comment]
Maybe, in which case the exposed sort method would need to tell on which column you are to make it possible to sort each column in a unique way.

**Comment by albertms10** [comment]
A soft solution to this may be just passing two values into the `rows` array: the raw one (`3217.58`, as a number) for sorting purposes and the to-be-displayed one (`"$3,217.58"`, as a string).

**Comment by metonym** [comment]
So the default sort method is fine – you just need a way to format the value as displayed in the UI?

**Comment by albertms10** [comment]
In this case, where a number gets displayed as a formatted string, it could be handled maybe by passing a display function to the header object:

```ts
import { number } from "svelte-i18n";

const headers = [
  {
    label: "Name",
  },
  {
    label: "Price",
    display: (value) => $number(value, { format: 'EUR' }),
  },
];

const rows = [
  {
    name: "John",
    price: 3217.58,
  },
];
```

But, in a case where a date value is involved, a custom `sort` function would be great, as you cannot sort properly _by default_ `"2020-09-21"` nor `"4 days ago"`. Something like the way is described in https://github.com/IBM/carbon-components-svelte/issues/282#issuecomment-698446919:

```ts
import dayjs from "dayjs";
import { date, number } from "svelte-i18n";

const headers = [
  {
    label: "Name",
  },
  {
    label: "Price",
    display: (value) => $number(value, { format: 'EUR' }),
  },
  {
    label: "Date",
    display: $date,
    sort: (a, b) => dayjs(a).isBefore(dayjs(b)),
];

const rows = [
  {
    name: "John",
    price: 3217.58,
    date: "2020-09-21",
  },
];
```

**Comment by albertms10** [comment]
@metonym, what do you think about this breaking change? Do you think of any other way to ‘relax’ the change to the `headers` object provided?

**Comment by metonym** [comment]
@albertms10  Based on the strength of the your use case, I find it difficult to disagree. And as you stated, it is not a breaking change so long as there are runtime checks that certain keys/methods are defined.

To reiterate, you propose an optional `sort` and `display` methods in the `headers` object?

Feel free to work on this and submit a PR

**Comment by albertms10** [comment]
Yes, summing up, both `sort` and `display` methods may be added to the `headers` object array.
