### ISSUE TITLE
Slider drag stops when the mouse moves off the line

### ISSUE THREAD

**Issue by bradphelan** [IBM/carbon-components-svelte#288]
See the video running in Microsoft Edge

https://ibm.github.io/carbon-components-svelte/?path=/story/slider--skeleton

![2020-09-28_18-43-49](https://user-images.githubusercontent.com/17650/94461750-d55b3000-01ba-11eb-9c87-1eda47ade727.gif)

Normally a slider will keep focus as long as the mouse is depressed. However here as soon as the pointer is not directly on the very thin line then the slider stops moving. This makes for very bad UX.

**Comment by bradphelan** [comment]
As a workaround you can add this to your css after loading the defaults from carbon

<style>
	/* Hack to mack the slider track thicker and easier to track */
	.bx--slider__track { height:1.125rem;}
	.bx--slider__filled_track { height:1.125rem;}
</style>

This makes the track thicker and the target doesn't go out of focus.

**Comment by metonym** [comment]
@bradphelan clever workaround with just CSS.

However, following your repo, the bug stemmed from the drag/touch events being limited to the slider input, when they should be attached to the document body.

Fixed and released in v0.15.0
