### ISSUE TITLE
Typescript for numeric slider exports value as type *string*

### ISSUE THREAD

**Issue by bradphelan** [IBM/carbon-components-svelte#289]
![image](https://user-images.githubusercontent.com/17650/94462593-0d16a780-01bc-11eb-966b-9c775ca5219d.png)

Given that min and max are all numbers this doesn't seem right.

**Comment by metonym** [comment]
Good catch. The Slider value prop is incorrectly typed here

**Comment by metonym** [comment]
[Fixed](https://github.com/IBM/carbon-components-svelte/blob/master/types/index.d.ts#L3826) and released in v0.15.0
