### ISSUE TITLE
add git hooks for prettier, prepack

### ISSUE THREAD

**Issue by josefaidt** [IBM/carbon-components-svelte#294]

**Comment by josefaidt** [comment]
@metonym per our discussion offline I will be adding `husky` and `lint-staged` to the project to ensure all files are ran through prettier before committing. 

As I am looking to see where we can fit `prepack` should the CSS build script happen after install? For contributors I believe this is a required step (generate CSS) before starting the storybook. On the same note, should the type definition creation be executed on a `pre-commit` git hook or a `prepublish` npm script?

My concern with the `pre-commit` git hook for type definition creation is that the developer will need to commit those files as well whereas `prepublish` will have them available for publishing, but not intended to be committed.

**Comment by metonym** [comment]
@josefaidt Thanks for leading this.

Let's keep the `prepack` command as is. We can mention in the development workflow to first build the styles.

The type definition generation should occur before publishing, so in the `pre-commit` hook. Currently, it serves as a "public API" for the library, so having the file be checked in is intended. For example, when new props are added to a component, I want to also verify that the types are correct as well.

**Comment by josefaidt** [comment]
> For example, when new props are added to a component, I want to also verify that the types are correct as well.

This makes a lot of sense. I'll make the necessary adjustments
