### ISSUE TITLE
Add Button icon prop position

### ISSUE THREAD

**Issue by albertms10** [IBM/carbon-components-svelte#298]
Add an `iconPosition` prop to the `Button` component in order to position its icon to the left or to the right, following the current icon implementation:

https://github.com/IBM/carbon-components-svelte/blob/bcc7058ddfa0278ac691c81ea853f628c7c92c42/src/Button/Button.svelte#L151-L158

**Comment by metonym** [comment]
For this, I feel that this should be controlled via CSS by the upstream, flagship carbon-components.

Could you propose this feature in the [Carbon repo](https://github.com/carbon-design-system/carbon/issues)?

**Comment by albertms10** [comment]
Described in https://github.com/carbon-design-system/carbon/issues/6970.

**Comment by albertms10** [comment]
Closing this issue as it does not align with IBM Design Language: https://github.com/carbon-design-system/carbon/issues/6970#issuecomment-705738883.

A simple workaround would be to manually position the icon as a child component (and specify some fancy CSS styles):

```svelte
<Button>
  <svelte:component this={ChevronLeft16} />
  <p>Label</p>
</Button>
```
