### ISSUE TITLE
Remove locales from flatpickr (DatePicker component)

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#313]
Locales for the DatePicker components shouldn't be preinstalled, developers can add them depending on their app requirements.
Removing locales from DatePicker saves 41972 bytes from the total **build** bundle size.

It's the second line in this file: https://github.com/IBM/carbon-components-svelte/blob/master/src/DatePicker/createCalendar.js
```
import l10n from "flatpickr/dist/l10n/index.js";
```

**Comment by metonym** [comment]
> saves 41972 bytes from the total build bundle size

To confirm, are you referring to the ESM/UMD bundles outputted to the `lib` folder?

Or is this after building your web app that uses the `DatePicker` component?

**Comment by weaseldotro** [comment]
Running `npm run build` outputs a .js file 41972 bytes smaller when not including localization.

**Comment by metonym** [comment]
Understood – in your PR, can you make `l10n` and optional parameter in `createCalendar`? https://github.com/IBM/carbon-components-svelte/blob/master/src/DatePicker/createCalendar.js#L50

**Comment by weaseldotro** [comment]
I'm afraid I don't understand. I want to remove the locales completely, I don't know how to make them optional in this repo.

I deleted the second line in the `createCalendar.js` and added the import for the locale I want in my own app, and it works fine - the bundle size is much smaller and the calendar contains my imported locale.

**Comment by metonym** [comment]
That's fine – draft a PR with locales removed. We'll need to update guidance on importing the user's preferred locale.
