### ISSUE TITLE
App switcher in UI Shell doesn't always close when clicking outside it

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#315]
Go to this demo: https://carbon-svelte.vercel.app/framed/UIShell/HeaderSwitcher
Open the app switcher in the UI Shell (top right button).
Click in the main window, anywhere between a few centimeters below the welcome text to the bottom of the page. So basically anywhere below `<main>`

This can be fixed by changing `<svelte:body` to `<svelte:window` in this line:
https://github.com/IBM/carbon-components-svelte/blob/master/src/UIShell/GlobalHeader/HeaderAction.svelte#L54

The app switcher is now closing, however I don't know if this has other consequences.

**Comment by metonym** [comment]
Open to PRs

**Comment by weaseldotro** [comment]
It seems that `<svelte:body>` is limited to the page body inside de browser window, while `<svelte:window>` uses the entire window. So if the page contents is smaller than the window, the rest of the window will not trigger the events defined on `<svelte:body>`

It looks like the same problem happens with the ComboBox component. So I did a search and the `<svelte:body>` is used in a bunch of components:
- ComboBox/ComboBox.svelte
- DatePicker/DatePicker.svelte
- Dropdown/Dropdown.svelte
- MultiSelect/MultiSelect.svelte
- OverflowMenu/OverflowMenu.svelte
- Slider/Slider.svelte
- Tooltip/Tooltip.svelte
- TooltipDefinition/TooltipDefinition.svelte
- TooltipIcon/TooltipIcon.svelte

Most of them use the click event, TooltipDefinition and TooltipIcon use keydown, while Slider uses a few others.
Should I make a PR and replace all the instances of `<svelte:body>` with `<svelte:window>`?

**Comment by metonym** [comment]
Start with the UI Shell header switcher

**Comment by phil-mayer** [comment]
@metonym I can still see this behavior in `MultiSelect/MultiSelect.svelte`. The MultiSelect control does not close as expected if the body is shorter than the window and the user clicks an area between the bottom of the body and the bottom of the window.

Can I open a PR to switch out `<svelte:body>` for `<svelte:window>` on this component?

**Comment by metonym** [comment]
@phil-mayer Yes

**Comment by weaseldotro** [comment]
Might as well replace all the instances of `<svelte:body>` that I listed in my last message :)

**Comment by phil-mayer** [comment]
Sure, happy to do so as long as @metonym is ok with the increase in scope.

**Comment by metonym** [comment]
Yes, let's be consistent and resolve this once and for all
