### ISSUE TITLE
ComboBox not filtering items for typed letters

### ISSUE THREAD

**Issue by skygate2012** [IBM/carbon-components-svelte#326]
When typing letters in the ComboBox it does not filter the items and pressing enter will result the selection of the first item. Is this the expected behavior? If so, is it possible to make the ComboBox work like MultiSelect?

![ComboBox](https://user-images.githubusercontent.com/7148976/95830897-e8e5c980-0d6a-11eb-8ce6-3368d0d2905e.gif)
![MultiSelect](https://user-images.githubusercontent.com/7148976/95830904-ebe0ba00-0d6a-11eb-8f3c-0c963b5e0275.gif)

**Comment by metonym** [comment]
@skygate2012 The combo box won't filter the list by default.

You'll need to provide your own filtering logic through the `shouldFilterItem` prop.

```svelte
<script>
const items = [{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]];

// The first parameter is the current item while the second parameter `value` is the current input value.
function shouldFilterItem(item, value) {
  return item.text.toLowerCase().includes(value.toLowerCase());
}
</script>

<ComboBox
  items="{items}"
  shouldFilterItem="{shouldFilterItem}"
  />
```

@metonym this should be documented

**Comment by skygate2012** [comment]
@metonym Thanks for the prompt reply! One more thing though, when loading the page there will be an error `TypeError: value is undefined`, I bypassed this by wrapping a try block, is there any workaround for this or am I doing it wrong?

**Comment by metonym** [comment]
@skygate2012 Thanks for pointing that out. Checking that the `value` is defined can be added to the filter function:

```
  function shouldFilterItem(item, value) {
    if (!value) {
      return true;
    }

    return item.text.toLowerCase().includes(value.toLowerCase());
  }
``

**Comment by skygate2012** [comment]
@metonym Thanks again!
