### ISSUE TITLE
ProgressIndicator currentIndex is not reactive to changing variables?

### ISSUE THREAD

**Issue by orta** [IBM/carbon-components-svelte#343]
Sandbox example: https://codesandbox.io/s/recursing-ride-e1781?file=/App.svelte:301-331

Hi! I've been enjoying this library, it's cool work. I wanted to use a `ProgressIndicator` to show, well, progress - but it doesn't seem to change the selection state when a `let` changes.  I am new to Svelte though, so it's possible I'm doing something wrong.

**Comment by metonym** [comment]
Hello @orta – thank you for raising this issue. This is definitely unexpected and not very "svelte-like." Several other components suffer from this, and need fixing (i.e. DatePicker).
