### ISSUE TITLE
Cannot use arrow and enter keys in TextArea when DatePicker is present

### ISSUE THREAD

**Issue by skygate2012** [IBM/carbon-components-svelte#345]
When both TextArea and DatePicker is present in one page, arrow and enter keys won't work in TextArea.

**Comment by pieterdv** [comment]
Noticed same behavior, it only occurs if datePickerType is set to, single or range, which leads me to think it has something to do with flatpickr that's interfering with keyboard events

**Comment by timeshift92** [comment]
node_modules/carbon-components-svelte/src/DatePicker/DatePicker.svelte:122

please change   appendTo by default    -- >datePickerRef,  but not document.body

**Before**
```
afterUpdate(() => {
    if ($hasCalendar && !calendar) {
      calendar = createCalendar({
        options: {
          appendTo,
          dateFormat,
          defaultDate: $inputValue,
          locale,
          maxDate,
          minDate,
          mode: $mode,
        },
```
after

```
 afterUpdate(() => {
    if ($hasCalendar && !calendar) {
      calendar = createCalendar({
        options: {
          appendTo:datePickerRef,
          dateFormat,
          defaultDate: $inputValue,
          locale,
          maxDate,
          minDate,
          mode: $mode,
        },
```

**Comment by alkanna** [comment]
Hey @timeshift92 would you mind making a pull request for this ?
