### ISSUE TITLE
ES5 Compatibility

### ISSUE THREAD

**Issue by DaleCam** [IBM/carbon-components-svelte#346]
First of all thank you so much for making such an awesome library freely available!
Im having trouble getting your rollup example working in older browsers that are ES5 compatible. I understand ES5 support is probably super low on your list at the moment, but I would even just love some advice!  
I have adapted the instructions here:
[https://github.com/carbon-design-system/carbon-web-components#browser-support](https://github.com/carbon-design-system/carbon-web-components#browser-support) by 1. adding babel transpilation to rollup.config.js:
```
  plugins: [
     ...
    !PROD && serve({ contentBase: ["public"], port: PORT }),
    !PROD && livereload("public"),
    PROD && terser(),
    babel({
      extensions: ['.js','.html','.mjs','.svelte'],
      include: ['src/**', 'node_modules/**']
    })
  ],
```
and this in babel.config.json:
```
{
    "presets": [
        ["@babel/preset-env"]
    ]
}
```
2. Added the polyfills to the top of index.js:
`import 'carbon-web-components/es/polyfills';`

It builds, however i get rollups "Unresolved dependencies" on all the polfills and I'm still getting a blank screen on older ES5 browsers. 
I feel I'm missing something here, so any help from anyone would be super appreciated!

**Comment by metonym** [comment]
Thanks @DaleCam . My initial reaction: have you installed the polyfills as project dependencies?

In the [carbon-web-components/es/polyfills file](https://github.com/carbon-design-system/carbon-web-components/blob/master/src/polyfills/index.ts#L13), there are a number of external dependencies, including `core-js`, `resize-observer-polyfill` and more.

**Comment by DaleCam** [comment]
Thank you so much for getting back to me @metonym!
Please excuse me if i'm missing something blaringly obvious. In addition to my first comments, I included "carbon-web-components" in  Package.json in the dependencies section:
```
   ...
  "dependencies": {
    "@babel/core": "^7.11.6",
    "@babel/plugin-transform-runtime": "^7.11.5",
    "@babel/preset-env": "^7.11.5",
    "@rollup/plugin-babel": "^5.2.1",
    "carbon-web-components": "^1.7.1"
  }
```
Is there another step I need to take to get this going? I will happily write a step by step guide somewhere in this documentation if we get this going! (If you want it that is!)

**Comment by metonym** [comment]
@DaleCam `carbon-web-components` does not ship with those polyfills (i.e. `core-js`). It has them as development dependencies for testing. In the [package.json](https://github.com/carbon-design-system/carbon-web-components/blob/master/package.json#L69), it only lists two direct dependencies.

As a result, you will need to add any polyfills for features you plan to support as direct dependencies in your project.

**Comment by DaleCam** [comment]
Thanks so much @metonym, I finally get it now! I'll add the polyfills as direct dependancies and provide an update shortly :)

**Comment by DaleCam** [comment]
@metonym thank you that worked a treat! 
As promised - if you think a step by step writeup on getting that going would be useful - just point me to where to do that and I can submit a pull request. 
Otherwise i can detail in this issue for future users that need this. Thanks again!

**Comment by metonym** [comment]
@DaleCam Great! That's a great topic for documentation – I think it may be better suited for the [carbon-web-components](https://github.com/carbon-design-system/carbon-web-components) since it pertains to that project directly.
