### ISSUE TITLE
TableToolbar

### ISSUE THREAD

**Issue by g5becks** [IBM/carbon-components-svelte#349]
Hi, are there plans to add a [TableToolbar](https://www.carbondesignsystem.com/components/data-table/usage/#table-toolbar) component? 

Thanks.

**Comment by metonym** [comment]
Yes, we plan to support it – tracking this in https://github.com/IBM/carbon-components-svelte/issues/14

**Comment by metonym** [comment]
@g5becks [v0.20](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.20.0) ships with four new components related to the TableToolbar: `Toolbar`, `ToolbarContent`, `ToolbarSearch`, `ToolbarBatchActions`.

Refer to the [DataTable docs](https://carbon-svelte.vercel.app/components/DataTable) for examples and usage.

  - [With toolbar](https://carbon-svelte.vercel.app/components/DataTable#with-toolbar)
  - [With toolbar (small size)](https://carbon-svelte.vercel.app/components/DataTable#with-toolbar-small-size)
  - [Selectable](https://carbon-svelte.vercel.app/components/DataTable#selectable)
  - [Initial selected rows](https://carbon-svelte.vercel.app/components/DataTable#initial-selected-rows)
  - [Selectable with batch actions](https://carbon-svelte.vercel.app/components/DataTable#selectable-with-batch-actions)
  - [Selectable (radio)](https://carbon-svelte.vercel.app/components/DataTable#selectable-radio)

Please note that the following are not yet supported (#14 ):

- Toolbar action menu (requires `OverflowMenu` floating menu to "break out" of the containing element)
- Filterable ToolbarSearch: opt-in filtering behavior where the value from Search filters the current rows
- Empty table cells: Appending an empty table cell to table body rows is useful for overflow menus

**Comment by g5becks** [comment]
This is great news!

**Comment by metonym** [comment]
In [v0.21](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.21.0), the following are supported:

- Toolbar action menu: use `ToolbarMenu`, `ToolbarMenuItem` components (existing DataTable examples w/ toolbars have been updated)
- Ability to add "empty columns" ([Example](https://carbon-svelte.vercel.app/components/DataTable#empty-column-with-overflow-menu)) which is useful for having an overflow menu per row
