### ISSUE TITLE
Import bug using vite

### ISSUE THREAD

**Issue by howesteve** [IBM/carbon-components-svelte#350]
Hello,

Using version 0.18 and vite with svelte plugin. If I use this import syntax (as suggested in components docs page):
``` typescript
<script>
  import { Button } from "carbon-components-svelte";
</script>

<Button>Primary button</Button>
```
... then I have this bug shown up on chrome:
```
Uncaught SyntaxError: The requested module '/@modules/flatpickr/dist/l10n/index.js' does not provide an export named 'default'
```

If use this syntax, everything works.
``` typescript
<script>
  import { Button } from "carbon-components-svelte/src/Button";
</script>

<Button>Primary button</Button>
```

**Comment by metonym** [comment]
See https://github.com/IBM/carbon-components-svelte/issues/249

The workaround is to create a `vite.config.js` and add `flatpickr` to the list of optimizable dependencies:

```js
// vite.config.js
module.exports = {
  optimizeDeps: {
    include: [
      "flatpickr",
      "flatpickr/dist/l10n/index.js",
      "flatpickr/dist/plugins/rangePlugin",
    ],
  },
};
```

**Comment by howesteve** [comment]
That worked, thanks. Somehow I missed it, I apologize.

**Comment by metonym** [comment]
No worries – that's on me. It needs to be documented.

Btw, since [version 0.16](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.16.0), the "flatpickr/dist/l10n/index.js" import can be omitted, thanks to @weaseldotro
