### ISSUE TITLE
Dropdown selectedIndex is not reactive

### ISSUE THREAD

**Issue by metonym** [IBM/carbon-components-svelte#353]
From https://github.com/IBM/carbon-components-svelte/issues/344

**Comment by metonym** [comment]
@orta In your [linked sandbox](https://codesandbox.io/s/peaceful-http-ok29x?file=/App.svelte), it seems that `transationalOptions` is passed as the `selectedIndex`.

I forked the CodeSandbox here: https://codesandbox.io/s/xenodochial-shape-vm0ol?file=/App.svelte

**Comment by orta** [comment]
I agree - looks like I got it wrong, thanks @metonym
