### ISSUE TITLE
Header component is rendering "undefined" if platformName is missing

### ISSUE THREAD

**Issue by howesteve** [IBM/carbon-components-svelte#357]
The title says it: if you miss the platformName property, the Header component will render an "undefined". I think it shouldn't render anything.
I'm using a 
```
<span slot="platform"></span> as workaround.
```
Besides, Header docs are missing on https://carbon-svelte.vercel.app/components/

Thanks

**Comment by metonym** [comment]
This is fixed in [v0.20](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.20.0).

`platformName` is now initialized as an empty string.
