### ISSUE TITLE
Yarn add is not working.

### ISSUE THREAD

**Issue by composite** [IBM/carbon-components-svelte#367]
Step to produce:
1. `yarn add -D carbon-components-svelte`

result:

```
error An unexpected error occurred: "https://registry.yarnpkg.com/carbon-icons-svelte/-/carbon-icons-svelte-10.17.0.tgz: ESOCKETTIMEDOUT".
```

`npm i -D carbon-components-svelte` does work.
but if I change to yarn (`yarn import`), it produces same error.

**Comment by metonym** [comment]
I'm unable to reproduce this.

AFAIK, even if your registry is set to "https://registry.yarnpkg.com", the installed packages should be resolved from "https://registry.npmjs.org" in the `yarn.lock` file.

My advice would be try using the latest version of `yarn`.

**Comment by composite** [comment]
I reinstalled `yarn`, retrying and done... missed.
