### ISSUE TITLE
Actions for events and more

### ISSUE THREAD

**Issue by timeshift92** [IBM/carbon-components-svelte#372]
Hello, see please see this action
https://github.com/AlexxNB/svelte-chota/blob/master/cmp/utils.js

**Comment by metonym** [comment]
Hi, could you provide more context?

**Comment by timeshift92** [comment]
see example https://svelte.dev/repl/a932802640b841c697896e6005babdc0?version=3.29.4
I think you can also make the skeleton an action to connect everywhere =)

**Comment by metonym** [comment]
Interesting, but using actions for skeleton states isn't practical because the semantic structure for skeletons can be vastly different.
