### ISSUE TITLE
Issue: Multi CodeSnippet in TabContent

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#373]
For some reason it doesn't render the show more button?

https://svelte.dev/repl/aeb9a69c761e441fb17d55f1232f3c10?version=3.29.4

**Comment by metonym** [comment]
You'll need more content. The show more button will only render if the `pre` element is a certain height. Right now, it's hardcoded to [>255](https://github.com/IBM/carbon-components-svelte/blob/master/src/CodeSnippet/CodeSnippet.svelte#L110).

**Comment by ispyinternet** [comment]
I've added more content (tab 2), can you check?

Cheers

**Comment by metonym** [comment]
That's a bug. It appears that it's not updating for visually hidden content.

**Comment by metonym** [comment]
I'll consider this a bug for now.

But a workaround would be to bind `selected` and render the code snippet when the tab is active (and the element's height can be computed): https://svelte.dev/repl/33cd6f89a0b34b0f8f7c0d11f1ad3d5a?version=3.29.4

**Comment by metonym** [comment]
After investigating, I stand by my earlier recommendation to re-render the component.

This is documented in the ["Hidden multi-line code" example](https://carbon-svelte.vercel.app/components/CodeSnippet#hidden-multi-line-code).
