### ISSUE TITLE
How does Header expandedByDefault work? 

### ISSUE THREAD

**Issue by markcheno** [IBM/carbon-components-svelte#374]
I would like to be able to hide the SideNav when in desktop mode by making the "toggle button" appear. I tried setting Header expandedByDefault=false, but it does not seem to work. The main content seems to expand, but the SideNav is still displayed. Is that a bug or am I doing something wrong?

`<Header company="IBM" platformName="Carbon Svelte" bind:isSideNavOpen expandedByDefault={false}>
`

**Comment by metonym** [comment]
Could you provide more context? Are you referring to the UI Shell `Header` component?

**Comment by markcheno** [comment]
@metonym Please see updated comment. I posted it accidently before I was finished.

**Comment by markcheno** [comment]
I would like this button displayed at all times to toggle the SideNav. Is this possible?

![image](https://user-images.githubusercontent.com/1900991/97516155-855dbd80-1960-11eb-801c-b835a953909d.png)

**Comment by metonym** [comment]
Understood.

Currently, the hamburger menu will only appear based on a hardcoded window width. However, I'm open to accommodating this use case. This could be done by exposing the window width threshold as a prop.

**Comment by markcheno** [comment]
Thank you for the extremely fast response. I think that would be a very useful feature.

**Comment by Sheepux** [comment]
Also make an option to not unfold automatically depending on the width ;)
That makes 3 options:
displayHamburgerMenu : always / ondemand / automatically

**Comment by ispyinternet** [comment]
same thing I was asking in https://github.com/IBM/carbon-components-svelte/issues/245 I think there would be demand for this!

**Comment by metonym** [comment]
Released in v0.23:

You can persist the UI Shell Header hamburger menu by setting `persistentHamburgerMenu` to `true`.

Usage example: https://carbon-svelte.vercel.app/components/UIShell#header-with-persisted-hamburger-menu
Rendered: https://carbon-svelte.vercel.app/framed/UIShell/PersistedHamburgerMenu?theme=g100
