### ISSUE TITLE
How to trigger an change event from the MultiSelect component

### ISSUE THREAD

**Issue by TKTheTechie** [IBM/carbon-components-svelte#378]
Hi,

I'm trying to figure out what events are triggered from the MultiSelect component.

https://carbon-svelte.vercel.app/components/MultiSelect

According to the docs, there are no forwarded or dispatched events. If so, how do I detect a change in selection?

**Comment by metonym** [comment]
Hi, there are forwarded events but no dispatched events. That would an enhancement, which could take inspiration from `ComboBox`.

To detect changes, have you tried to bind `selectedIds`?


```svelte
<script>
  import { MultiSelect } from "carbon-components-svelte";

  let selectedIds = [];
  $: console.log(selectedIds);
</script>

<MultiSelect
  titleText="Contact"
  label="Select contact methods..."
  items={[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]}
  bind:selectedIds
/>
```

**Comment by TKTheTechie** [comment]
I see - yes, that would work.

 I was looking at the react component https://react.carbondesignsystem.com/?path=/docs/multiselect--default and saw there was an onChange function there and just wanted to make sure I wasn’t missing anything on the svelte one

**Comment by metonym** [comment]
The "select" event is dispatched in v0.22.

For the record, I would not recommend using dispatched events to *manage* state. The "Svelte way" is to bind on certain props. For `MultiSelect`, it would be `selectedIds`. However, I acknowledge that in certain cases dispatched events may be useful.

**Usage**

```svelte
<MultiSelect on:select={(e) => { console.log(e.detail); }} />
```

**Signature**

```ts
interface Detail {
  selectedIds: string[];
  selected: Item[];
  unselected: Item[];
}
```

**Example (Chrome)**

![multiselect](https://user-images.githubusercontent.com/10718366/97746449-906f3580-1aa7-11eb-989d-328e394dede2.png)
