### ISSUE TITLE
Question about Modal

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#383]
Modal has an open property. I was surprised when I looked at the markup to see the modal markup was present but just hidden, if you were to seed your app with many modals (to be fair probably not significant!) but markup would grow.

Are there any reasons / design decisions for this? I suppose perhaps to enable css transitions?

I had assumed the Modal would wrap the following pseudo code:

```svelte
{#if open}
<div>Markup</div>
{/if}
```
Cheers!

**Comment by metonym** [comment]
> Are there any reasons / design decisions for this? I suppose perhaps to enable css transitions?

Yes, mostly for the CSS fade in / fade out effect.

It's definitely up to the consumer for whether or not to actually render the Modal code.

**Comment by ispyinternet** [comment]
probably easy to test, but you could answer any other potential pitfalls, should one do:?

```svelte
{#if open}
<Modal bind:open />
{/if}
```

**Comment by metonym** [comment]
Yes, that should work

**Comment by ispyinternet** [comment]
In which case i would question why you don't pull that inside to the component code? Seems a weird pattern to expose in user land. Minor details, and probably reasons beyond my station, certainly not trying to pick any faults!

**Comment by ispyinternet** [comment]
> In which case i would question why you don't pull that inside to the component code? Seems a weird pattern to expose in user land. Minor details, and probably reasons beyond my station, certainly not trying to pick any faults! 

Or when you say should work, do you mean without transitions?

**Comment by metonym** [comment]
Yes, without transitions. It will just instantly "appear" and "disappear"
