### ISSUE TITLE
All svelte transitions should be disabled by default

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#384]
I think all svelte transitions should be disabled by default, and the developer should choose whether to use a transition and which one they should use. I found svelte transitions in `HeaderAction` and `HamburgerMenu`.

Some developers want to optimize their user interfaces so they're super fast, so they don't want any transitions at all. Others would maybe want to use other transitions than those currently hard-coded in the library.

Such a feature can be can be easily implemented using the `in` and `out` directives: https://svelte.dev/examples#in-and-out and custom js transitions: https://svelte.dev/examples#custom-js-transitions

Update: in my initial message I didn't specify svelte transitions, just "transitions". I updated this message to reflect that I meant svelte transitions.

**Comment by metonym** [comment]
Currently, the transitions are controlled via CSS from `carbon-components`. FWIW, Carbon also uses the [prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) API to reduce animations if the user opts in. For example, if `prefers-reduced-motion` is triggered, the Skeleton states will not animate.

As for overriding transitions, would the following work?

```css
* {
  transition-duration: 0 !important;
}
```

**Comment by weaseldotro** [comment]
Sorry, I meant svelte transitions, as in those specified using the `transition` directive: https://svelte.dev/tutorial/transition
I have updated the issue title and my initial message to reflect this.

**Comment by metonym** [comment]
I stand corrected – you're right.

I find it difficult to disagree.

**Comment by metonym** [comment]
@weaseldotro 

Released in [v0.25](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.25.0):

- the fly transition for HamburgerMenu has been removed
- disable the `HeaderAction` transition by setting `transition` to `false` [Usage example](https://carbon-svelte.vercel.app/components/UIShell#header-with-app-switcher)

> I think all svelte transitions should be disabled by default

I'll consider this for the next major release.

**Comment by weaseldotro** [comment]
Nicely done. I suppose you have to keep this feature in sync with the parent carbon library, so maybe some transitions must remain. But it's fine as long as they can be disabled by the developer.
