### ISSUE TITLE
Multiple ComboBox display issue

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#388]
https://codesandbox.io/s/stupefied-shadow-0we3p

Click on the second `ComboBox`, then click on the first one. The second one doesn't close, and the first one's content is displayed underneath the second one content.

The problem/solution is in `ListBox.svelte`, line 62. By removing the `stopPropagation` directive, the event is forwarded to the parent element and caught by `<svelte:window on:click>`. However I don't know if there are any other consequences. Also, I haven't tried using `Dropdown` but I'm guessing the problem persists there also, since it also uses `ListBox`.

**Comment by metonym** [comment]
Patched in v0.23.1
