### ISSUE TITLE
Where's FluidForm?

### ISSUE THREAD

**Issue by edge37v** [IBM/carbon-components-svelte#389]
Error: 'FluidForm' is not exported by node_modules\carbon-components-svelte\src\index.js

**Comment by metonym** [comment]
What `carbon-components-svelte` version are you using?

**Comment by edge37v** [comment]
0.12

**Comment by edge37v** [comment]
Upgraded to 0.12.3. Still didn't

**Comment by metonym** [comment]
FluidForm was released in [v0.15.0](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.15.0). Could you upgrade to v0.15 or greater?

**Comment by edge37v** [comment]
Upgraded to 0.22. Works now. Thanks
