### ISSUE TITLE
docs: use rich text formatting in Component API Props description

### ISSUE THREAD

**Issue by albertms10** [IBM/carbon-components-svelte#390]
It may be better to parse the description field in the Component API Props documentation to show code text as `code` instead of \`code`:

<img width="761" alt="docs with plain text" src="https://user-images.githubusercontent.com/26429103/98445101-234a4880-2116-11eb-9f5b-d5afebac38c2.png">

<img width="762" alt="docs using code tag" src="https://user-images.githubusercontent.com/26429103/98445103-25aca280-2116-11eb-9516-df59a3274606.png">

A simple RegExp replace method should be enough, if a string can be parsed as HTML:

```ts
"`hasIconOnly` must be set to `true`.".replace(/`(.*?)`/g, "<code>$1</code>");
// Output: "<code>hasIconOnly</code> must be set to <code>true</code>."
```

So, in [ComponentApi.svelte:115](https://github.com/IBM/carbon-components-svelte/blob/8c304521691c3e25a1670e3f73d18cc9c59ee5cc/docs/src/components/ComponentApi.svelte#L115),

https://github.com/IBM/carbon-components-svelte/blob/8c304521691c3e25a1670e3f73d18cc9c59ee5cc/docs/src/components/ComponentApi.svelte#L114-L116

`line` should be appended with the replace method described above:

```svelte
<div class="description">{@html line.replace(/`(.*?)`/g, "<code>$1</code>")}.</div>
```

**Comment by metonym** [comment]
Noted

**Comment by albertms10** [comment]
May I open a PR?

**Comment by metonym** [comment]
Sure
