### ISSUE TITLE
ProgressIndicator, currentIndex is still not reactive

### ISSUE THREAD

**Issue by miedzikd** [IBM/carbon-components-svelte#399]
Releted issues: #343 , #344 

Sandbox example: https://codesandbox.io/s/sharp-cache-1m3cc?file=/App.svelte (fork from old issue with updated dependencies)

Hi! You're doing a great job .. I have been using your library since yesterday and I liked it a lot ...

I saw that in v0.19.0 you were working on the above mentioned issue. Unfortunately, I still cannot programmatically (e.g. with a button at the bottom of the page) jump to the next step.

**Comment by metonym** [comment]
Released in v0.23.

Usage example: https://carbon-svelte.vercel.app/components/ProgressIndicator#programmatic-usage
Rendered: https://carbon-svelte.vercel.app/framed/ProgressIndicator/ProgrammaticProgressIndicator?theme=g100
