### ISSUE TITLE
hasIconOnly Button renders `undefined` tooltip

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#400]
It looks like `hasIconOnly` implicitly requires a tooltip. If you don't supply `iconDescription` you get 'undefined' text.

Is this the way? (anticipating a star wars reply ;)

**Comment by metonym** [comment]
This is the correct behavior. An icon-only button must have a tooltip description.

**Comment by ispyinternet** [comment]
Don't you mean: 'This is the way'

(sorry - cant get mandalorian out my head )

**Comment by metonym** [comment]
@ispyinternet 

This is the correct behavior

*_waves hand in a poor imitation of Obi Wan's Jedi mind trick_
