### ISSUE TITLE
Export ComboBoxItem Type Interface

### ISSUE THREAD

**Issue by jquesada2016** [IBM/carbon-components-svelte#409]
I am not sure if it was intentional or accidental, but the component documentation lists [here](https://github.com/IBM/carbon-components-svelte/blob/master/COMPONENT_INDEX.md#combobox) the items prop type as ComboBoxItem, but there is no such type exposed. It was not until I went to node_modules\carbon-components-svelte\types\ComboBox/ComboBox.d.ts and read the type there to see the expected type.

Could this type please be exposed via an export?

**Comment by metonym** [comment]
Patched in v0.23.2
