### ISSUE TITLE
Grid Column padding

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#410]
Do you think the Column component should support a `padding` prop to apply the class `bx--col-padding`?

**Comment by metonym** [comment]
Yes – a boolean `padding` prop to Column and Row components for vertical padding would be nice.

Would you like to work on this?

**Comment by metonym** [comment]
Released in [v0.25](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.25.0)

[Usage example](https://carbon-svelte.vercel.app/components/Grid#padded-columns)

[Rendered](https://carbon-svelte.vercel.app/framed/Grid/PaddedGrid?theme=g100)
