### ISSUE TITLE
Ordered Lists Larger than 100 Items Overflows Onto Text

### ISSUE THREAD

**Issue by jquesada2016** [IBM/carbon-components-svelte#418]
I noticed working with some larger ordered datasets, when more than 100 `ListItems` are present in an `OrderedList`, and nothing but plain text or `<p>` is inside `ListItem`, the numbers overflow on top of the content.

## How to Reproduce
```
<OrderedList>
  {#each Array(1000) as _}
    <ListItem>This is a test list</ListItem>
  {/each}
</OrderedList>

```

**Comment by metonym** [comment]
Hello, can you try setting `native` to `true` on the `OrderedList`? That will enable the native browser styles.

```svelte
<OrderedList native>
  {#each Array(1000) as _}
    <ListItem>This is a test list</ListItem>
  {/each}
</OrderedList>
```

**Comment by jquesada2016** [comment]
Hello,

Thank you for the suggestion. It does get rid of the overflow issue. Thank you very much!
