### ISSUE TITLE
Fix FileUploader types

### ISSUE THREAD

**Issue by miedzikd** [IBM/carbon-components-svelte#421]
FileUploader component types are not valid:

current state:
```
Files: string[];
```

should be:
```
Files: FileList
```

output from console:
![image](https://user-images.githubusercontent.com/21012696/100422555-d14c7100-308a-11eb-955e-6dc1c86742a4.png)

**Comment by metonym** [comment]
Released in [v0.25](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.25.0)
