### ISSUE TITLE
DataTable props vs Grid props?

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#425]
For example:

`<Grid padding narrow />` 

vs

`<DataTable size="compact" />`

I much prefer the first, and as a developer there is a bit of fatigue, I understand size is enum but could there be a resolution strategy for `<DataTable compact tall />` or can you force a compile error?

**Comment by metonym** [comment]
For me, it's the opposite.

I'm more fatigued by having to remember all the size booleans. I think it's important – from a design perspective – to distinguish between boolean and enum props. An enum would delineate all possible values with a single prop type.

Furthermore, consider the Button component, which has a size and kind prop. I feel that having booleans for each variant is not practical.

```js
 /**
   * Specify the kind of button
   * @type {"primary" | "secondary" | "tertiary" | "ghost" | "danger" | "danger-tertiary" | "danger-ghost"}
   */
  export let kind = "primary";

  /**
   * Specify the size of button
   * @type {"default" | "field" | "small"}
   */
  export let size = "default";
```

**Comment by ispyinternet** [comment]
fair enough - I figured that was a long shot, just came of the back of a good 20 page refreshes wondering why `<DataTable compact />` wasn't compact 😩
