### ISSUE TITLE
HeaderSearch: Clicking a result fires the select event with the wrong result

### ISSUE THREAD

**Issue by tommy4st** [IBM/carbon-components-svelte#429]
Where?
https://carbon-svelte.vercel.app/components/UIShell (Header with global search)

What?
When I search and click on a result to select it, the wrong result is used in the fired select event. Instead of the clicked result, the first result is always returned.

**Comment by metonym** [comment]
Thank you for reporting this. Patched in [v0.25.1](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.25.1)
