### ISSUE TITLE
Add preventDefault to HeaderSearch

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#431]
In the search input in `HeaderSearch`, the `on:keydown` function should include a `preventDefault` function to stop the cursor in the input to moving to the start or the end of the value when pressing `ArrowDown` or`ArrowUp`.

**Comment by metonym** [comment]
Would you like to work on this?

**Comment by weaseldotro** [comment]
I’m AFK for a couple of days, that’s why I created the issue.
