### ISSUE TITLE
Header hamburger button should be optional

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#434]
Currently it always shows the button on small displays, even if there is no side nav. From [the documentation](https://www.carbondesignsystem.com/components/UI-shell-header/usage):

> Hamburger menu: The hamburger icon is used to open product navigation such as the left panel. The hamburger menu is only needed when there is a collapsable left navigation.

The example given on that page also has no side menu.

Since the navigation component is specified outside the header, it might be necessary to add a separate property or make `isSideNavOpen` have three meaningful states and use that to hide the button (it could accept `null` or `undefined` for example, maybe should be the default then).

**Comment by jquesada2016** [comment]
I 100% agree with this observation.
