### ISSUE TITLE
Toggle disabled behaviour

### ISSUE THREAD

**Issue by ispyinternet** [IBM/carbon-components-svelte#453]
I see as part of your audit, we now have toggled as a reactive.

Prior to this, I was using a click handler, and one observation was that after setting the component state to disabled the `on:click` handler still fired. Do you think this should be the behaviour? 

Obviously now if we react to the toggle state this gets cleaned up, but...?

I would add that although the toggled reactive solves this case in some cases, there are others (like my use case) where you are rendering a list of Toggle's and adding a click handler binding to a row id. That's not so easy to solve, by binding some behaviour to the toggled state, unless we bind to a specially constructed array to map component to row id?

**Comment by metonym** [comment]
The `toggled` prop has always been reactive.

**Comment by ispyinternet** [comment]
oh has it, I was just glossing over this and assumed not (btw did you see my edit above, and also thoughts on click when disabled?)

> Documentation
> 
> Reactive examples:
> 
> Search (bind value)
> ContentSwitcher (bind selectedIndex)
> Toggle (bind toggled)

**Comment by metonym** [comment]
Even if the toggle is disabled, the `on:click` event should be forwarded as is. If the user chooses to manage state using the dispatched events, the onus is on them to also mind if the toggle is disabled.

I just assumed that two way binding is the de facto method of managing state. It's what makes Svelte so appealing in the first place.

**Comment by metonym** [comment]
For the Search, ContentSwitcher, Toggle components, all I did in that reactive audit was to document simple examples that illustrate two way binding. It's always been possible to bind those values.

**Comment by ispyinternet** [comment]
> Even if the toggle is disabled, the `on:click` event should be forwarded as is. If the user chooses to manage state using the dispatched events, the onus is on them to also mind if the toggle is disabled.
> 
> I just assumed that two way binding is the de facto method of managing state. It's what makes Svelte so appealing in the first place.

fair enough.
