### ISSUE TITLE
Header props

### ISSUE THREAD

**Issue by alicantokdemir** [IBM/carbon-components-svelte#462]
So right now rest props are being applied on a element instead of the header so we can't able to pass any props such as a custom style and seems like only way is to override bx--header class. Is this intended? Thanks

```
<header role="banner" aria-label="{ariaLabel}" class:bx--header="{true}">
  <slot name="skip-to-content" />
  {#if ($shouldRenderHamburgerMenu && winWidth < 1056) || persistentHamburgerMenu}
    <HamburgerMenu bind:isOpen="{isSideNavOpen}" />
  {/if}
  <a
    href="{href}"
    class:bx--header__name="{true}"
    bind:this="{ref}"
    {...$$restProps}
    on:click
  >
    {#if company}
      <span class:bx--header__name--prefix="{true}">{company}&nbsp;</span>
    {/if}
    <slot name="platform">{platformName}</slot>
  </a>
  <slot />
</header>
```

**Comment by metonym** [comment]
Yes, in this specific case it was intended.

The reasoning is that the `a` element has more arbitrary props that a consumer may want to control. It does feel inconsistent because some components `$$restProps` is top-level.
