### ISSUE TITLE
DataTable Guidance: ComboBox / Dropdown Single Selection

### ISSUE THREAD

**Issue by LaughingBubba** [IBM/carbon-components-svelte#470]
Hi and thanks for the tremendous work on this project.

I'm new to CDS so I'm wondering if its possible to have a combo box of single values (floating above column header) to use to filter the table similar to:

https://www.carbondesignsystem.com/patterns/filtering#selection-methods

If not what idiom should I apply?

Cheers and thanks in advance.

**Comment by LaughingBubba** [comment]
So after RTFM'ing, the answer is: use the slots!

```html
    <span class="flex-wrap" slot="cell-header" let:header>
      {#if header.key === 'panel_name'}
        <div style="flex:wrap;" on:click|stopPropagation><PanelFilter /></div>
      {:else}{header.value}{/if}
    </span>
```
The only issue is that `DropDown`, `MultiSelect` etc are bubbling their `on:click` events, hence the `on:click|stopPropagation` above as selecting items triggers sorting on `sortable` `<DataTables/>`

**Comment by LaughingBubba** [comment]
So after RTFM'ing, the answer is: use the slots!

```html
    <span class="flex-wrap" slot="cell-header" let:header>
      {#if header.key === 'panel_name'}
        <div style="flex:wrap;" on:click|stopPropagation><PanelFilter /></div>
      {:else}{header.value}{/if}
    </span>
```
The only issue is that `DropDown`, `MultiSelect` etc are bubbling their `on:click` events, hence the `on:click|stopPropagation` above as selecting items triggers sorting on `sortable` `<DataTables/>`

**Comment by metonym** [comment]
@LaughingBubba If you're referring to the [UI in this example](https://www.carbondesignsystem.com/static/8b7c51ed71c96be4c5822a5a0c6001f6/392b1/filter-1.png), that appears to use the `Dropdown` and `StructuredList` components.
