### ISSUE TITLE
OverflowMenu styling and focus invalid when opened for the first time

### ISSUE THREAD

**Issue by ebeuker** [IBM/carbon-components-svelte#476]
When the overflow menu is opened for the first time:
- The menu contains a border
- The first menu item is not selected
![image](https://user-images.githubusercontent.com/754901/103478646-6ea46e80-4dc8-11eb-9f78-8ed654b12db8.png)

When you open the over flow menu for a second or third time:
- The menu no longer contains a border
- The first menu item is selected
![image](https://user-images.githubusercontent.com/754901/103478730-fab69600-4dc8-11eb-8d95-69b6e9bfbf65.png)

I think that this issue has been introduced with the fix for issue #191

**Comment by metonym** [comment]
Published to NPM in v0.27
