### ISSUE TITLE
$$restProp for TextInput

### ISSUE THREAD

**Issue by miedzikd** [IBM/carbon-components-svelte#480]
I think will be great if we add $$restProp for TextInput... html input element have many more properties and is really hard to handle all of them... e.g. min, max, step etc... 

what do you think @metonym ? If you agreed then I can work on that :) 

Greetings!
Daniel

**Comment by metonym** [comment]
Agreed. Looking forward to the PR

**Comment by miedzikd** [comment]
agrh... now I realize that TextInput already use {...$$restProps} in div wrapper... 
so my change will broke dependents apps ;/

[Here ](https://developer.mozilla.org/pl/docs/Web/HTML/Element/Input) you can find complete list of available input attributes. It is really huge... 

In my opinion it is better to add `restProps` to input because without it we lose functionality at this point. It is easier to replace `restProps` on a wrapper with an additional external wrapper. Unfortunately, this is not possible with input attributes ...

what do you think @metonym ?

**Comment by metonym** [comment]
Again, I agree.

`$$restProps` should be forwarded to the "significant" element of a component. By "significant," I mean the element that the consumer would most likely want to pass attribute values to.

It's a breaking change, but one that is necessary.

This library is still <v1 so it's fine if a minor version contains breaking changes.

**Comment by miedzikd** [comment]
Done :)

**Comment by metonym** [comment]
Published to NPM in v0.27
