### ISSUE TITLE
Cannot specify classes in ModalHeader

### ISSUE THREAD

**Issue by tommy4st** [IBM/carbon-components-svelte#482]
In [ModalHeader](https://github.com/IBM/carbon-components-svelte/tree/master/src/ComposedModal/ModalHeader.svelte) there are several Props to specify classes, but as the [Svelte documentation](https://svelte.dev/docs#class_name) shows they only allow to toggle the prop name as a class.

For example here:
```svelte
    <p
      class:bx--modal-header__heading="{true}"
      class:bx--type-beta="{true}"
      class:titleClass
    >
```

For `titleClass` instead of adding the value of this prop as a class, it's name is only added as a class, if the prop contains any truthy value.

**Comment by metonym** [comment]
Published to NPM in v0.27
