### ISSUE TITLE
Add class attribute to Grid, Row and Column component

### ISSUE THREAD

**Issue by miedzikd** [IBM/carbon-components-svelte#483]
Hi :) Right now one of svelte plugin removes unused styles if classes are added to Grid, Row or Column components...
Im guessing that this is because these components don't have class attribute described in the interface

What do you think about adding class attribute there @metonym?

```
Plugin svelte: Unused CSS selector ".custom-column-class"
```

**Comment by metonym** [comment]
> don't have class attribute described in the interface

Are you referring to the TS definitions? The [props extend the `div` HTML attributes](https://github.com/IBM/carbon-components-svelte/blob/master/types/Grid/Grid.d.ts#L3), so you should be able to pass any valid attribute for a div element.

**Comment by miedzikd** [comment]
sorry ... I got mixed up with the projects :P 

I thought that in some components the passed class is recognized by a plugin that removes the unused css code, and in some not ... but now when I check it, I think I dreamed about it :D
