### ISSUE TITLE
NumberInputs floating point error with small step

### ISSUE THREAD

**Issue by jhwz** [IBM/carbon-components-svelte#486]
If I do:
```
<NumberInput
type="number"
min={0}
max={1}
value={0.01}
step={0.001}
invalidText="Number must be between 0 and 1"
/>
```
When you increment the value a few times it starts to diverge from multiples of 0.001

**Comment by metonym** [comment]
Floating point step values are supported in [v0.70.13](https://github.com/carbon-design-system/carbon-components-svelte/releases/tag/v0.70.13).

[Example](https://carbon-components-svelte.onrender.com/components/NumberInput#with-step-value)
