### ISSUE TITLE
Add function for specifying keys to Dropdown

### ISSUE THREAD

**Issue by mrme44** [IBM/carbon-components-svelte#492]
In earlier versions this worked fine (probably anything before [#358 ](https://github.com/IBM/carbon-components-svelte/issues/358)), but now after upgrading to version 0.26.0 the following:

    <Dropdown items={ [[0, 'Item A'], [1, 'Item B']] } itemToString={item => item[0]} />

produces the error

> Cannot have duplicate keys in a keyed each

As soon as I click on the dropdown.

I think the best thing to do would be to add a parameter to ComboBox, Dropdown, and MultiSelect components that behaves like `itemToString` but for getting keys instead of items.

**Comment by metonym** [comment]
`items` type is expected to be `{ id: string; text: string; }[]`.

**Comment by mrme44** [comment]
I guess I'm just used to using component libraries that don't care about how your data is formatted. I made items look like that and it worked. Thank you.
