### ISSUE TITLE
TextInput on:input misbehaviour

### ISSUE THREAD

**Issue by myangga** [IBM/carbon-components-svelte#494]
Hi,

I was trying to change from:

`<input type="text" bind:value={user.email} on:input={updateUser} >`

to

`<TextInput bind:value={user.email} on:input={updateUser} />`

First is absolutely functional. But second is behaving like so: every 2 letters typed is disappearing...
As it was linked to firebase I'm testing with, I tried a more simple example like below:

```
<script>
...
let textInputData = "";

const alertText = () => {
  console.log(textInputData);
}
...
</script>
...
<TextInput bind:value={textInputData} on:input={alertText} placeholder="Type anything" />
<input type="text" bind:value={textInputData} on:input={alertText} placeholder="Type anything">
...
```

Now I don't see letter disappearing but console log with TextInput is always one letter behind while log always match with html input.
Do you know this issue? Any workaround?

**Comment by metonym** [comment]
Is it possible to do something like this?

```script
$: if (textInputData) console.log('change', textInputData);
```

**Comment by myangga** [comment]
@metonym Many thanks. Just works ;-)
