### ISSUE TITLE
Event forwarding of Select component

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#501]
The component exposes `change` and `blur` but *not* `focus`.

Also, the `input` event might be relevant as it behaves differently to `change`. MDN:

> The input event is fired every time the value of the element changes. This is unlike the change event, which only fires when the value is committed, such as by pressing the enter key, selecting a value from a list of options, and the like.

The key related events like `keydown` maybe should be forwarded as well, in case the default selection behavior needs to be changed for some reason.

**Comment by metonym** [comment]
What is your current workaroundv

**Comment by brunnerh** [comment]
@metonym I did not need those events yet; i just noticed that they were missing.

As a workaround one could either use the `ref` prop to attach events manually or maybe wrap the component in a `div` and capture the event there, if they bubble up.

**Comment by metonym** [comment]
Fixed in v0.40.1
