### ISSUE TITLE
Scroll inside Tile component

### ISSUE THREAD

**Issue by peopledrivemecrazy** [IBM/carbon-components-svelte#503]
I have a component like this
![image](https://user-images.githubusercontent.com/3922469/106432589-f1d2e600-6494-11eb-9936-307009b0c124.png)

```html
 <Tile style="overflow-y:scroll;position: relative;">
            <p>Top 10 tweets</p>
            <Tweets />
 </Tile>
```

Tweet component is set to a constant height and has `overflow-y:scroll` and the scroll just won't work if I wrap `<Tweets/>` inside the Tile component and without it the scroll works fine.

**Comment by metonym** [comment]
This is a CSS question, but you should set a max height on the tile component to allow its child to overflow.

**Comment by peopledrivemecrazy** [comment]
```html
<Tile>
            <p>Top 10 tweets</p>
            <Tweets />
 </Tile>
 ```
 
 This doesn't work? The `Tweets` component has a max height set and overflow scroll.

**Comment by metonym** [comment]
the element that has overflow-y should have the max height.

**Comment by peopledrivemecrazy** [comment]
> the element that has overflow-y should have the max height.

Thanks, I can verify this works 🚀
