### ISSUE TITLE
use carbon components as custom elements

### ISSUE THREAD

**Issue by nosovk** [IBM/carbon-components-svelte#507]
Svelte could be compiled to custom elements - https://svelte.dev/docs#Custom_element_API

Could we use carbon select as web component somehow?

Purpose: allow to use backend template engine (like php) to render beautiful carbon components instead of default selects for example.

how to do that:
- need to add separate bundle with different rollup settings, that will redistribute webcomponents bundle via npm
  - do we need bundle with all components included or better to publish one bundle per one component?
- some examples needed how to embed web components using https://unpkg.com/ and custom tags (svelte repls)

**Comment by metonym** [comment]
Dupe https://github.com/IBM/carbon-components-svelte/issues/467

Also, there appears to be a dedicated effort to implement Carbon as web components: https://github.com/carbon-design-system/carbon-web-components

Does that suit your needs?

**Comment by nosovk** [comment]
yep, thanks! Will try to mix it with custom svelte components for now
