### ISSUE TITLE
[ASK] - How do I display the loading indicator with a message?

### ISSUE THREAD

**Issue by lamualfa** [IBM/carbon-components-svelte#508]
Very great framework. I love this.

> Sorry. I asked this in the issue tab because there is no tab to open the discussion. maybe you should open the discussion tab as a place to ask questions.

<hr>

## How do I display the loading indicator with a message below?

I use it to display messages when user data is being verified.

<hr>

## Why i am not use the Skeleton component?

The reason is i didn't find a skeleton component for the menu. and another reason is because each user has a different side nav menu. for admin I will try to open the whole menu. and for normal users I will close some menus.

<hr>

### My Code

`WithAuth.svelte` (Use as Component Wrapper)

![image](https://user-images.githubusercontent.com/39755201/106857112-27c0d600-66f2-11eb-8774-265bdc5aaca1.png)

### Output

![sss](https://user-images.githubusercontent.com/39755201/106857636-fc8ab680-66f2-11eb-846f-12fef33f24a2.gif)

**Comment by metonym** [comment]
Two ways:

- hide the loading overlay (`<Loading withOverlay={false} />`)
- elevate the z-index for the toast notification

  ```svelte
  <div style="z-index: 999999999">
    <ToastNotification />
  </div>

  <Loading />
  ```

**Comment by lamualfa** [comment]
@metonym Thanks. But, is the toast suitable for use in that case?

**Comment by metonym** [comment]
Well, it depends. Usually I use notifications for success/error states, so AFTER the actual loading state finishes.

**Comment by lamualfa** [comment]
@metonym Thank you very much.
