### ISSUE TITLE
Cannot use <Form on:submit|preventDefault> 

### ISSUE THREAD

**Issue by rccc** [IBM/carbon-components-svelte#519]
Is there a way ot have some documentation about this ?
Thanks in advance.

**Comment by metonym** [comment]
It's not possible to apply a modifier to an event that's forwarded to a component.

You'll need to do `on:submit={(e) => { e.preventDefault(); }}`.

However, the [`Form` component](https://github.com/IBM/carbon-components-svelte/blob/master/src/Form/Form.svelte) already applies the `preventDefault` modifier.

**Comment by rccc** [comment]
@metonym 
Many thanks for your kind answer !
