### ISSUE TITLE
DatePicker: cannot use other language than English

### ISSUE THREAD

**Issue by myangga** [IBM/carbon-components-svelte#520]
Hi,
I tried below code in my app:
```
<DatePicker
            required
            invalidText="Champs requis"
            datePickerType="single"
            locale="fr"
            dateFormat="d/m/Y"
            bind:value={contact.birth_date}
            style="margin-bottom:1rem"
            >
            <DatePickerInput
                labelText="Date de naissance"
                placeholder="jj/mm/aaaa"
            />
</DatePicker>
```

But date picker is not french is not displayed. Any other language than english is not working.
I checked that flatpicker node module is properly installed and it's ok, with locale files available.

**Comment by weaseldotro** [comment]
Did you import the locale file into your svelte component? I do this inside the `<script>` tag:
```js
import 'flatpickr/dist/l10n/ro.js'
```

**Comment by myangga** [comment]
It defintely works! many thanks @weaseldotro . Short reference inside documentation may help others ;-)
