### ISSUE TITLE
Cannot use class or style properties in DataTable with typescript

### ISSUE THREAD

**Issue by DemiusAcademius** [IBM/carbon-components-svelte#524]
When I add class or style properties in DataTable (and some others components) with typescript, I got error:
```
Type '{ headers: { key: string; value: string; }[]; rows: ClientDetalii[]; class: string; }' is not assignable to type 'IntrinsicAttributes & DataTableProps'.
  Property 'class' does not exist on type 'IntrinsicAttributes & DataTableProps'
```

**Comment by DemiusAcademius** [comment]
Also I can not add id property. Thus, I cannot customize the display of the table. For example, its width

**Comment by metonym** [comment]
Besides the DataTable, what are the other components?

**Comment by DemiusAcademius** [comment]
I am at a loss to answer. I checked my small pet- project and it seems like the typescript is swearing nowhere. But I remember that somewhere styles or class were ignored. Sorry for my (google translate) English.
