### ISSUE TITLE
ComposedModal is hard coded for two buttons and does not support hiding [x]

### ISSUE THREAD

**Issue by insasho** [IBM/carbon-components-svelte#528]
This is a feature request.

I am attempting to use a ComposedModal for the following use case:
* When a user clicks on a tab which requires authentication, present the user a modal.
* The modal is a barrier: the modal should not be closeable (no [X], and clicking outside should not close the dialog).
* The user must click one of the buttons corresponding to authentication providers to proceed (e.g. "Sign in with Google", "Sign in with Twitter", ...).
* There are three buttons.
* I must be able to discriminate the handlers for the buttons.

This use case mirrors the [Carbon Login](https://www.carbondesignsystem.com/patterns/login-pattern) pattern.

ComposedModal doesn't support this use case well because:
1. While you can preventCloseOnClickOutside, the [X] cannot be disabled.
2. The [ModalFooter](https://github.com/IBM/carbon-components-svelte/blob/master/src/ComposedModal/ModalFooter.svelte) is hard coded for two buttons. [Carbon specs for Modal](https://www.carbondesignsystem.com/components/modal) suggest that more than two should be allowed.

As a workaround, I've implemented a modified version of ModalFooter which renders a ButtonSet, but this feels like something that the core components should support.

Thanks!

**Comment by metonym** [comment]
Related #472 

It looks like [Carbon now supports three button modals](https://github.com/carbon-design-system/carbon/pull/7775) as of version 10.29, but it's yet to be implemented in this library.

**Comment by metonym** [comment]
Support for three button modals via the `secondaryButtons` prop released in [v0.39](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.39.0)
