### ISSUE TITLE
Missing card component

### ISSUE THREAD

**Issue by blazzjosh** [IBM/carbon-components-svelte#531]
Well done guys....but It seems that a few many components are missing like cards, etc.

**Comment by metonym** [comment]
What "card" component are you referring to?

**Comment by blazzjosh** [comment]
Ref: https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/card

**Comment by metonym** [comment]
Currently, this library aims to implement [Carbon components](https://github.com/carbon-design-system/carbon/tree/master/packages/components).

Carbon for IBM.com is a separate implementation.

**Comment by blazzjosh** [comment]
right....

**Comment by ItsiAdam** [comment]
@metonym does IBM have any plans to implement the "community components" in Svelte? If not, I may consider publishing something myself.

**Comment by metonym** [comment]
@ItsiAdam No plans – go ahead
