### ISSUE TITLE
OverflowMenuItem default text

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#537]
The component has this property which has a placeholder text:

```js
/**
 * Specify the item text
 * Alternatively, use the default slot for a custom element
 */
export let text = "Provide text";
```

But when using the default slot, the `text` property will not change and still be used for the `title` attribute by default. This seems unexpected.

![image](https://user-images.githubusercontent.com/834235/109187774-837efc00-7792-11eb-95e4-77caf23ed5ee.png)

Maybe it should just be set to undefined/empty string to prevent this.

**Comment by metonym** [comment]
Fixed in v0.40.1
