### ISSUE TITLE
remove default title value for InlineNotification

### ISSUE THREAD

**Issue by cupcakearmy** [IBM/carbon-components-svelte#552]
Just a small one. Is it by design that the `InlineNotification` has a default value for the title? it's kind of weird and counter intuitive having to explicitly setting the `<InlineNotification kind="info" title="" />` to remove it.

I can do a PR if you like :)

**Comment by metonym** [comment]
The ugly default value is meant to signal to the consumer to change it. It looks like you have a great workaround of setting `title` to an empty string.

**Comment by cupcakearmy** [comment]
@metonym if it is by design feel free to close the issue (and the related PR).
IMO it's a bit counter intuitive 🙂

**Comment by brunnerh** [comment]
Unusable defaults on things that are not immediately obvious are bad. Things like this could easily slip through and end up in production. See also #537

**Comment by cupcakearmy** [comment]
@brunnerh I agree, there should be no text unless a dev actually specifies it.
To be honest in the case of the notification there is no way it would end up in production as if you only want to use the description you will see the default title value popping up.
Still feel like it should be empty.

**Comment by cupcakearmy** [comment]
I don't care to much either, just wanted to point it out as a user of the library :)
I'll leave it up to you to decide, maybe there is an actual guideline in the general cabron them, havn't looked at the react/vue versions
