### ISSUE TITLE
OverflowMenu within a form is triggering form submit event

### ISSUE THREAD

**Issue by sharpcodepro** [IBM/carbon-components-svelte#554]
If you place OverflowMenu inside a Form, opening the menu is causing submit event on the form.

This happens because the button does not have a type attribute and hence defaults to "submit". A very simple markup to reproduce this is given below.

`<form on:submit={()=>{console.log("submitted")}}>
<OverflowMenu flipped>
                <OverflowMenuItem
                  on:click={() => {
                  }}
                  type="button"
                  danger
                  text="Delete"
                />
              </OverflowMenu>
</form>`

Now I have solved this by checking submitted in form submit event but this is not ideal as it depends on carbon internals

`if (e.submitter.className.indexOf("bx--overflow-menu") > -1) return;`

**Comment by metonym** [comment]
Fixed in v0.40.1
