### ISSUE TITLE
[FEATURE REQUEST] Please allow the user to specify classes to the components

### ISSUE THREAD

**Issue by silvioprog** [IBM/carbon-components-svelte#556]
Hi.

Consider the following naive example:

```svelte
<script lang="ts">
  import { Button } from "carbon-components-svelte/src"; // See note [1] for "src"
</script>

<Button hasIconOnly class="test">Test</Button>

<style>
  .test {
    position: absolute;
    top: 0;
    right: 0;
  }
</style>
```

It would allow to specify the component styles into styles area instead of inline style, i.e, allowing to enjoy the IDE features like highlighting, code completion etc., however, the code above raises the following error:

```
Unused CSS selector ".test"
 5:
 6: <style>
 7:   .test {
      ^
 8:     position: absolute;
 9:     top: 0;
```

and doesn't work, i.e any style are applied via classes attribute. The same behavior in other components (Link, Accordion, Form etc.).

Please allow the user to specify classes for who wants to use them.

cheers

Note[1] Using "`src`" to avoid errors like `<Button> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules`.

**Comment by cupcakearmy** [comment]
@silvioprog this has nothing to do with this library 🙂
It's a general discussion whiting Svelte and is simply not possible ATM. 
If you are interested you can read up here https://github.com/sveltejs/svelte/issues/2870
Carbon components actually does pass the classes down

[Example](https://svelte.dev/repl/7eb9c76bdaf7434399aee66d58c0db3e?version=3.35.0):
```svelte
<script>
  import { Button } from "carbon-components-svelte"
</script>

<div>
	<Button class="my">Lets Go</Button>
</div>

<style>
  div :global(.my) {
    position: absolute;
    top: 0;
    right: 0;
  }
</style>
```

**Comment by cupcakearmy** [comment]
Also about your note. Have you put `carbon-components-svelte` inside you `devDependencies` and not the normal? This is very important with Sapper :)

**Comment by silvioprog** [comment]
@cupcakearmy Thank you very much for so detailed information. After applying the code as you suggested, it worked like a charm in my test (including the `devDependencies` one). Now I'm going to use Carbon in my projects! 😃

**Comment by cupcakearmy** [comment]
@silvioprog No prob :) The thing with putting stuff in the dev dep. should be in the docs. I also discovered by trial and error. 
If you care about the why: if a dep is in the dev deps, sapper will look for the "svelte" entry in the package.json. See [here e.g.](https://github.com/IBM/carbon-components-svelte/blob/master/package.json#L7) and it compiles the source. This is the reason that you were importing from 'carbon-components-svelte/src' :)

**Comment by silvioprog** [comment]
@cupcakearmy +1 for putting this info to the docs. 🙂

Thank you!
