### ISSUE TITLE
[FEATURE REQUEST] Checkbox - Making labelText a slot

### ISSUE THREAD

**Issue by flaviolivolsi** [IBM/carbon-components-svelte#563]
I'm working on a project that needs a checkbox with a link within the text (privacy policy agreement). I think it would be useful to make the checkbox label a slot, or anyway to do something in order to allow that.

Any thoughts?

Cheers

**Comment by metonym** [comment]
Agreed – it should be slottable.

In fact, I feel that any input component with a labelText/titleText should be slottable. This would be useful for rending a TooltipIcon, for example.

**Comment by metonym** [comment]
Released in v0.36.0
