### ISSUE TITLE
DataTable search

### ISSUE THREAD

**Issue by zeljkosh** [IBM/carbon-components-svelte#579]
Does data table support search out of the box, or does it need to be added manually ?

Also when using something like this 

` <ToolbarSearch
            expanded
            bind:value={searchFieldValue}
            on:input={() => {
              console.log(searchFieldValue);
            }}
          />`

The first time when i enter some value (lets say letter A) console log returns empty string, but every other key press is returned properly. same thing happens with the TextInput, but for example using basic html text input returns expected result.
I dont understand why the first key press is ignored, while all others are properly registed.

**Comment by metonym** [comment]
1) Manually

2) When using the toolbar search, I bind to the value (as you did) and then listen to changes like such:

```svelte
<script>
  $: if (value) doSomething();
</script>
```

**Comment by zeljkosh** [comment]
Thanks, your example works flawlessly.
