### ISSUE TITLE
$$restProps behavior on FileUploader differs from documentation

### ISSUE THREAD

**Issue by vaishnavsm** [IBM/carbon-components-svelte#582]
The documentation at `https://carbon-svelte.vercel.app/components/FileUploader` says that:
```
$$restProps
FileUploaderButton spreads $$restProps to the input element.
```

However, $$restProps are spread over the container div, not the input element.
For example, line 79 of FileUploader.svelte has:
```
<div
  class:bx--form-item="{true}"
  {...$$restProps}
  on:click
  on:mouseover
  on:mouseenter
  on:mouseleave
>
```

Simple fix, but:
1. Is this intended behavior (maybe the docs are outdated/wrong)
2. Should this be fixed, given the api may have been used by others?

Also, would it be a good idea to check for this in other components too? I've checked all the file upload components, and this applies to all of them. TextInput and PasswordInput have $$restProps on the input element, as expected.  Maybe there are others where this error exist too.

Would be more than happy making a PR for this if it's worth it :)

**Comment by vaishnavsm** [comment]
I got a bit confused here I believe. The doc only says that FileUploaderButton spreads $$restProps on the input, which is correct. So maybe the spreading of $$restProps on the div is intentional, but undocumented behavior? #344 suggests that FileUploader isn't properly documented, so this is probably the case.

**Comment by metonym** [comment]
Those are two separate components

- restProps is forwarded to the input element in `FileUploaderButton`, which is intended
- restProps is forwarded to a div element in `FileUploader`, which is intended

**Comment by vaishnavsm** [comment]
Ah ok. Thanks!
