### ISSUE TITLE
"Setting 'name' property on NumberInputs breaks forms

### ISSUE THREAD

**Issue by jhwz** [IBM/carbon-components-svelte#584]
### Issue
`name` property not correctly forwarded

If setting the name property on a `NumberInput` element expect to be able to retrieve the value from the form. This does not currently work.

```
<script>

function handleSubmit(e){
      var form = new FormData(e.target);
    
     // This part doesn't work
     let val = form.get("numberinput");
    ....
}

</script>


<Form on:submit={handleSubmit}>

   <NumberInput name="numberinput" value={12} />

<Form>
```

### Fix 
Forward the name property to the input. Already fixed in #568

**Comment by metonym** [comment]
Merged #568 and released in v0.31.1
