### ISSUE TITLE
Examples need to be revamped

### ISSUE THREAD

**Issue by metonym** [IBM/carbon-components-svelte#599]

**Comment by weaseldotro** [comment]
When redoing the example, also please take into consideration an example on how to include only the css required for the components that the project uses.
For example, if a project only uses the `TextInput` and `Button` components, when building for production it should generate the carbon css only for these components (and obviously any dependencies).

**Comment by metonym** [comment]
@weaseldotro Excellent suggestion – I'll track that in a separate issue.
