### ISSUE TITLE
can't open a dropdown with the keyboard

### ISSUE THREAD

**Issue by jasonlyu123** [IBM/carbon-components-svelte#607]
## Step to reproduce

It can be reproduced on the docs site. 
1. Navigate to any dropdown example
2. Hold the tab key until it focuses on a dropdown
3. Press the enter key to activate the dropdown

It would open and be closed immediately. I think it's because the button also bubbles a click event so that it got toggled twice. One in click handler and another in a keydown handler. Seems like a preventDefault can fix this. I can open a PR for this if you like to.

**Comment by metonym** [comment]
Thank you for raising this issue – PR would be appreciated.
