### ISSUE TITLE
DataTable: add 'display' attribute on DataTableCell when using slots

### ISSUE THREAD

**Issue by rafadess** [IBM/carbon-components-svelte#609]
I miss a feature when passing components to cell slots on DataTable.

When using DataTable you can create a header object with a 'display' attribute where you can place a function to format you data before showing. This features is very handy but ifyou pass a component to slot 'cell', the let:cell doesn't have this attribute. So you have to format it inside of the component you are passing. It would be nice if 'display' attribute be passed to let:cell.

I've done that by changing line 160 on DataTable.svelte file:

from:
`  $: rows = rows.map((row) => ({
    ...row,
    cells: headerKeys.map((key) => ({ key, value: row[key] })),
  }));`

to:
`$: rows = rows.map((row) => ({
    ...row,
    cells: headerKeys.map((key, index) => ({
      key,
      value: row[key],
      display: headers[index].display,
    })),
  }));`

Then on lines 368-369 and 381-382 I've replaced `headers[j].display` to `cell.display`. Also I've updated the types.ts and the jsdocs for the DataTableCell Object.

Is it fine to consider a PR?

**Comment by metonym** [comment]
Can you provide some sample code to better illustrate this?

**Comment by rafadess** [comment]
Sure.

```
const formatDate = (date) => new Date(date).toLocaleString()
const headers = [
        { key: 'taskName', value: 'Task Name'},
        { key: 'creationDate', value: 'Creation Date', 'display': formatDate},
    ]
const rows = [
        { taskName: 'MyTask', creationDate: 1619049103652 }
    ]

<!--The value that will be display will take in consideration the function passed on formatDate-->
<DataTable {headers} {rows} />

<DataTable {headers} {rows}>
    <span slot="cell" let:cell>
        {cell.value}  <!--This will print the raw value, without considering the function on 'display'-->
        {cell.display(cell.value)} <!-- This doesn't work because 'cell' doesn't have 'display' attribute. The PR would add the 'display' attribute to cell object.-->
    </span>
</DataTable>
```

Of course I could use the function directly on the component that I'm passing:

```
<DataTable {headers} {rows}>
    <span slot="cell" let:cell>
        {formatDate(cell.value)}
    </span>
</DataTable>
```

But since we may passed this value on the header object, it would be handy to have it in the cell object.

**Comment by metonym** [comment]
@rafadess Excellent – I understand completely and think this would be very convenient. Looking forward to the PR.
