### ISSUE TITLE
Contributing Documentation: Set upstream with https instead of ssh

### ISSUE THREAD

**Issue by rafadess** [IBM/carbon-components-svelte#616]
I was working on a PR and when I tried to fetch my repo with the master upstream I got a permission denied error. The problem was I had added the upstream with ssh url:

`git remote add upstream git@github.com:IBM/carbon-components-svelte.git`

[This stackoverflow post](https://stackoverflow.com/questions/13587787/permission-denied-publickey-on-github-when-fetching-from-upstream) explains that I would need to use the ready-only link, which is https. It worked after changing to:

`git remote add upstream https://github.com/IBM/carbon-components-svelte.git`

 Would it be ok to update contributing.md to use https? [Only one line would be changed.](https://github.com/IBM/carbon-components-svelte/compare/master...rafadess:contributing-guidelines-update)

**Comment by alkanna** [comment]
I did not have this problem. This may be a problem if you use git with HTTP and have not setup your ssh keys though. Is that the case ?

**Comment by alkanna** [comment]
That may be because you initially cloned the repo using http and not ssh.

**Comment by rafadess** [comment]
@alkanna Thank you for your help.

Just found the issue here. I had multiples ssh keys and git was trying to use a different one that I had here on GitHub. I figure it when I was trying to first clone with ssh and it was not working, even though the repo was in my account. :(

So this is not a real issue. Thanks for your support!

Rafa

**Comment by alkanna** [comment]
Hey @rafadess I suggest you use a proper ssh config, that will avoid such cases :)
https://gist.github.com/rbialek/1012262
