### ISSUE TITLE
Nested tooltip get cut

### ISSUE THREAD

**Issue by sinedie** [IBM/carbon-components-svelte#623]
Hey there. Awesome work.

Im trying to create a menu on the side bar and some elements needs a tooltip. The thing is that the tooltip gets crop, like this:

![image](https://user-images.githubusercontent.com/43920544/116961721-b4cfe880-ac69-11eb-9078-1a86eabeaeb9.png)

Is this hows suppose to be?. Even if the container was a div, it gets crop. It shouldn't render in front of everything? no matter the size of the container?

menu.svelte
```
<script>
	import component from "./component.svelte";
       ...
<script>

<SideNav>
       <component />
</SideNav>
```

component.svelte
```
<Tooltip direction="right" triggerText="text" >
      description
</Tooltip>
```

**Comment by metonym** [comment]
Unfortunately, this is a limitation of the current implementation. The tooltip menu is contained within the parent, so it risks getting cropped. Unlike what Carbon React does, it's not a true "floating menu."

As a workaround, I'd recommend experimenting with the tooltip direction/alignment props.

**Comment by sinedie** [comment]
Yeah, I had to align the tooltips in another way and minimize text inside them. Even like that, I save a lot of time with this library, so. Im good. Ty for the anwser, closing it.
