### ISSUE TITLE
Using optimizeCarbomInports in svelte kit

### ISSUE THREAD

**Issue by xSCIven** [IBM/carbon-components-svelte#627]
Svelte.config.js -> the configuaration file for svelte kit projects does not support CJS

You cannot import optimizeCarbonImports without getting errors
```
import optimizeCarbonImports from "carbon-components-svelte/preprocess/index.js"
```

Furthermore there are no typings for optimizeCarbonImports. 

This module is currently incompatible with svelteKit until optimizeCarbonImports can be resolved to ES

**Error**
Error in svelte.config.js

ReferenceError: module is not defined

**Comment by metonym** [comment]
Thanks for reporting this – I'm currently awaiting approval to open source a collection of Carbon Svelte preprocessors with CJS + ESM support.

**Comment by xSCIven** [comment]
@metonym What is the timeline for that?

**Comment by metonym** [comment]
@xSCIven [carbon-preprocess-svelte](https://github.com/IBM/carbon-preprocess-svelte)

**Install**

```sh
yarn add -D carbon-preprocess-svelte
```

**Usage**

```js
// svelte.config.js
import { optimizeImports } from "carbon-preprocess-svelte";

export default {
  preprocess: [optimizeImports()],
};
```

**Comment by SGarno** [comment]
I am struggling with somewhat of a similar issue.   I have it working with the above pre-processor directives for the components, however, I can't seem to get it to work for using carbon styles using SCSS.    The following error occurs:

`GET http://localhost:3000/carbon-components-svelte/css/all.scss net::ERR_ABORTED 404 (Not Found)`

### app.html ###
```
<!DOCTYPE html>
<html lang="en">

<style lang="scss">
	@import 'carbon-components-svelte/css/all.scss';
</style>

<head>
	<meta charset="utf-8" />
	<link rel="icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	%svelte.head%
</head>

<body>
	<div id="svelte">%svelte.body%</div>
</body>

</html>
```

### svelte.config.js ###
```
/** @type {import('@sveltejs/kit').Config} */
import { optimizeImports } from "carbon-preprocess-svelte";
import sveltePreprocess from 'svelte-preprocess';

const config = {
	preprocess: [
		optimizeImports(),
		sveltePreprocess()],
	kit: {
		target: '#svelte'
	}
};

export default config;
```

I can get it to work if I change to plain css and directly access the node_module directory, but this does not seen right.   This works:

### app.html using CSS from ../node-modules/... ###
```
<!DOCTYPE html>
<html lang="en">

<style lang="css">
	@import '../node-modules/carbon-components-svelte/css/all.css';
</style>

<head>
	<meta charset="utf-8" />
	<link rel="icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	%svelte.head%
</head>

<body>
	<div id="svelte">%svelte.body%</div>
</body>

</html>
```


Anyone able to get this to work with sveltekit and carbon scss?

**Comment by metonym** [comment]
@SGarno I don't use SCSS, but I believe that the style block should be in a Svelte file for it to be preprocessed.

Example:

```svelte
<!-- routes/__layout.svelte -->
<slot />

<style lang="scss">
  @import "carbon-components-svelte/css/all.scss";
</style>
```

**Comment by SGarno** [comment]
@metonym   I figured it out...you did the same thing I tried first and it didn't work.    It has to be without the .scss extension and that was tripping me up.


```html
<style lang="scss">
	@import 'carbon-components-svelte/css/all';
</style>

```
