### ISSUE TITLE
Focus stuck on filterable MultiSelect when changing focus to other text input

### ISSUE THREAD

**Issue by hansrodtang** [IBM/carbon-components-svelte#635]
Probably related to #540, which fixed this for fieldRef, but the problem still persists for [inputRef](https://github.com/IBM/carbon-components-svelte/blob/cff16e5d7de19652df6a905360bbfe01ea6d0d7f/src/MultiSelect/MultiSelect.svelte#L387:L394).

**Comment by Grandnainconnu** [comment]
Same problem here, it keeps the focus when it shouldn’t

**Comment by metonym** [comment]
Fixed in v0.38.0
