### ISSUE TITLE
Dynamic theme with sveltekit

### ISSUE THREAD

**Issue by SGarno** [IBM/carbon-components-svelte#651]
In the README it shows that there is a way to change the theme by updating the HTML attribute using javascript.

```HTML
<script>
  /** @type {"white" | "g10" | "g90" | "g100"} */
  let theme = "white";

  $: document.documentElement.setAttribute("theme", theme);
</script>

<button on:click="{() => (theme = 'g90')}">Update theme</button>
```

This only works on the client (non SSR or in onMount).

How could this be used inside a component with sveltkit?

**Comment by SGarno** [comment]
Found a way to make this work through localStorage and onMount.   With SK, document is only available in onMount.

### header.svelte (truncated)
```javascript
	import { onMount } from 'svelte';
	import { get } from 'svelte/store';
	import { theme } from '../stores/theme.js';

	onMount(() => {
		if (!get(theme)) {
			theme.set(defaultTheme);
		}
		let themeUnSub = theme.subscribe((value) => {
			// If localstore was deleted under the covers, then reset to default
			if (value === null) {
				value = defaultTheme;
			}

			console.log('Updating theme to ' + value);
			document.documentElement.setAttribute('theme', value);
		});

		return () => {
			themeUnSub();
		};
	});
```

The above code was used in conjunction with https://github.com/joshnuss/svelte-local-storage-store for managing the theme setting in local storage.

**Comment by OG84** [comment]
But what if we already want to render the <html theme=".." on server side (based on a cookie or something) to prevent flicker?
