### ISSUE TITLE
Forward key events for TextArea 

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#665]
I am missing `keydown` in particular. But `keyup` and `keypress` should probably be forwarded for consistency as well.

Other input fields appear to forward `keydown` but not the other two, is there a good reason not to forward those?

**Comment by metonym** [comment]
I agree – the TextArea is missing a forwarded keydown event.

[keypress is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Element/keypress_event)

**Comment by metonym** [comment]
Fixed in v0.36.0
