### ISSUE TITLE
ComboBox items syntax doesn't make sense to me

### ISSUE THREAD

**Issue by geoidesic** [IBM/carbon-components-svelte#681]
https://carbon-svelte.vercel.app/components/ComboBox

It shows items like this:
```
<ComboBox
  titleText="Contact"
  placeholder="Select contact method"
  items={[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]}
/>
```

But what is that crazy syntax? An array inside a keyless object?? 
And how would I break that out as a variable in a component. E.g.
```
<script>
let items = ???   //<---- wtf do I put here?
</script>

<ComboBox
  titleText="Contact"
  placeholder="Select contact method"
  {items}
/>
``` 
Similarly this:
```
<Slider
  labelText="Runtime memory (MB)"
  min={10}
  max={990}
  maxLabel="990 MB"
  value={100}
/>
```
How would I bind a value to that? This doesn't work e.g.
```
<script>
let sliderValue = 50;
</script>
<Slider
  labelText="Runtime memory (MB)"
  min={10}
  max={990}
  maxLabel="990 MB"
  value={sliderValue}
/>
```

**Comment by brunnerh** [comment]
That is just basic Svelte syntax. Have a look at [the tutorial](https://svelte.dev/tutorial) if you haven't.

The curly braces do not mean "object", they interpolate any JS. (Setting an object would require two pairs of curly braces.)

So in the caes of the `ComboBox`, you just set items to an array:

```js
let items = [{ id: '0', text: 'Slack' }, ...]
```

In the case of the Slider you need two-way binding. By default it only sets the value on the component, so it does not propagate back from it. The syntax would be `bind:value={sliderValue}`.

[[codesandbox demo]](https://codesandbox.io/s/681-smey6?file=/App.svelte)

**Comment by geoidesic** [comment]
Ok maybe I don't understand Svelte. I understood the curly braces for Svelte to represent something that would be replaced, i.e. a placeholder. But in the case of the sample I posted there's nothing to replace, so I don't understand why this wouldn't work:
```
<ComboBox
  titleText="Contact"
  placeholder="Select contact method"
  items=[{ id: '0', text: 'Slack' }, { id: '1', text: 'Email' }, { id: '2', text: 'Fax' }]
/>
```
In other words why do we need the braces if there's nothing that needs replacing?

I've noticed that even scalar values are surrounded with placeholders, which isn't necessary in svelte:
```
<Slider
  labelText="Runtime memory (MB)"
  min={10}
  max={990}
  maxLabel="990 MB"
  value={100}
/>
```
The above doesn't give you anything more than the below (as far as I can tell):
```
<Slider
  labelText="Runtime memory (MB)"
  min=10
  max=990
  maxLabel="990 MB"
  value=100
/>
```
And if you're marking scalars with braces, then why not also the string?

**Comment by brunnerh** [comment]
I guess you can think of it like this: Anything that is *not* enclosed in `{}` is interpreted as a string, which is how most HTML works anyway. Even the `input` element attributes `min`, `max` and `value` are typed as string (they get converted at some point internally, though, depending on the `type`.)

Also it's not just scalars that you use it for, so often you need some kind of delimiter anyway. E.g. if you want a relative value range you could have something like:

```svelte
<Slider
  min={min}
  max={min + 100} />
```

> And if you're marking scalars with braces, then why not also the strings? (e.g. maxLabel={"990 MB"})

Well, you *can* do that, it's not wrong. But given that string is the default interpretation, that is simply a bit redundant.

**Comment by geoidesic** [comment]
https://stackoverflow.com/questions/68051031/why-does-svelte-put-curly-braces-on-scalars
