### ISSUE TITLE
ContextMenu demo in docs isn't working

### ISSUE THREAD

**Issue by geoidesic** [IBM/carbon-components-svelte#684]
https://carbon-svelte.vercel.app/components/ContextMenu

Just shows a blank area.
<img width="1320" alt="Screenshot 2021-06-19 at 01 58 36" src="https://user-images.githubusercontent.com/4637995/122626335-e0842200-d0a1-11eb-90f6-d31ebf5fc13d.png">

**Comment by metonym** [comment]
Try right clicking within the iframe.

![context](https://user-images.githubusercontent.com/10718366/122627115-70a27700-d062-11eb-9e46-857dfd462a96.png)

**Comment by geoidesic** [comment]
LOL.. seems I forgot what a ContextMenu is 🤣

**Comment by geoidesic** [comment]
Ok but now it really isn't working...

<img width="700" alt="Screenshot 2021-06-27 at 09 32 37" src="https://user-images.githubusercontent.com/4637995/123538041-9eef1900-d72a-11eb-8505-8a0ab01f4a7e.png">

**Comment by metonym** [comment]
Fixed in v0.38.0
