### ISSUE TITLE
Side nav button superfluous for rail side nav?

### ISSUE THREAD

**Issue by brunnerh** [IBM/carbon-components-svelte#699]
On small screens it sill seems to show the button in the header, which does nothing except showing the overlay.

From [the example](https://carbon-svelte.vercel.app/components/UIShell#header-with-side-navigation-rail):
![image](https://user-images.githubusercontent.com/834235/123531514-77398a00-d705-11eb-86d6-62266d8e2ca1.png)

**Comment by metonym** [comment]
Fixed in v0.38.0
