### ISSUE TITLE
Version 0.37.0 is not in the npm repository

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#701]
Version 0.37.0 was released yesterday but cannot be downloaded from npm, latest version there is 0.36.0
https://www.npmjs.com/package/carbon-components-svelte?activeTab=versions

![Screenshot 2021-06-27 at 15-17-08 carbon-components-svelte](https://user-images.githubusercontent.com/1822852/123544195-d5448c80-d75a-11eb-9259-f5a440a7c105.png)

**Comment by metonym** [comment]
Re-attempted the publish. Please try again

**Comment by weaseldotro** [comment]
It's working now, thanks.
