### ISSUE TITLE
Select is not implementing {...$$restProps}

### ISSUE THREAD

**Issue by gufoscuro** [IBM/carbon-components-svelte#703]
Hi!,
as per title, it seems that `Select` is not implementing `{...$$restProps}`, therefore, if I try to set a custom attribute, like a  `data-testid`, that won't be there on the `<select>` item as it applies for other components, like `TextInput`

Is this on purpose or is it just missing and will be possibly be fixed?

thanks

**Comment by metonym** [comment]
restProps is forwarded to the top-level element:

https://github.com/IBM/carbon-components-svelte/blob/master/src/Select/Select.svelte#L83

**Comment by gufoscuro** [comment]
ok thanks.
