### ISSUE TITLE
TextInput and TextArea readonly false not working

### ISSUE THREAD

**Issue by RicardoValero95** [IBM/carbon-components-svelte#710]
Both TextInput and TextArea aren't editable even with readonly false. NumberInput works fine. 

https://codesandbox.io/s/textinput-readonly-issue-t1if2

**Comment by metonym** [comment]
It seems that `input` elements can only have a `readonly` attribute or no value at all.

From a UX perspective I'd consider this a bug, but a workaround would be to set it to  `readonly={readonly ? true : undefined}`.

**Comment by RicardoValero95** [comment]
I was using `readonly = null` as a workaround. Thanks.

**Comment by RicardoValero95** [comment]
Seems like TextInput readonly works in 0.38.1, TextArea doesn't.

**Comment by metonym** [comment]
Fixed in v0.38.2
