### ISSUE TITLE
Define width to collapse header menu into hamburger menu

### ISSUE THREAD

**Issue by banglashi** [IBM/carbon-components-svelte#715]
Hi there,

would it be possible to change the hardcoded 1056px to be a prop?

Thanks

https://github.com/IBM/carbon-components-svelte/blob/0d3090b1239ab79d017d00db65b011828aa2c184/src/UIShell/GlobalHeader/Header.svelte#L60

**Comment by metonym** [comment]
@banglashi 

In [v0.39](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.39.0), you can now override the default breakpoint width using the `expansionBreakpoint` prop.

Give it a shot and let me know if there are any issues.

**Comment by banglashi** [comment]
Hi @metonym 
thanks, that works fine. Now another question arised regarding the `HeaderNav` that should hide at the same `expansionBreakpoint` as the `Header` shows the HamburgerMenu. Is that something that makes sense?
