### ISSUE TITLE
TreeView - expose expanded node IDs the same way as selected nodes

### ISSUE THREAD

**Issue by dqzx** [IBM/carbon-components-svelte#750]
It would be useful if there was a reactive prop for expandedIds the same way as there is for selected nodes via selectedIds. It would allow for a simple way to persist the current state of the TreeView.

**Comment by metonym** [comment]
Released in v0.41.0.

The [Initial expanded nodes](https://carbon-svelte.vercel.app/components/TreeView#initial-expanded-nodes) example has been updated to use the new `expandedIds` prop.
