### ISSUE TITLE
Geometry & Symmetry of components (TextInput, ComboBox, Button) in a Grid 

### ISSUE THREAD

**Issue by ibilux** [IBM/carbon-components-svelte#754]
Hello,
I'm trying to get the geometry and symmetry of some components in a grid right.
The TextInput component is good and stretched over the grid.

But, the ComboBox is small and  did not stretch over the grid. How to fix this ?

Also, how to set the length of the two columns of ComboBox & Button? 

The usual `flex: 100%;` and `width: 100%;` styles didn't work for me in carbon.

My code:

```
<script>
  import { Grid, Row, Column, TextInput, ComboBox, Button } from 'carbon-components-svelte';
</script>

<Grid>
  <Row style="outline: 1px solid var(--cds-interactive-04)">
    <TextInput labelText="Street" />
  </Row>
  <Row style="outline: 1px solid var(--cds-interactive-04)">
    <ComboBox titleText="Type" helperText="Sets the default type." />
  </Row>
  <Row style="outline: 1px solid var(--cds-interactive-04)">
    <Column style="outline: 1px solid var(--cds-interactive-04)">
      <ComboBox titleText="Terms" helperText="Sets the default terms." />
    </Column>
    <Column style="outline: 1px solid var(--cds-interactive-04)">
      <Button size="small">Configure Terms</Button>
    </Column>
  </Row>
</Grid>
```

![Screenshot_2021-07-16_12-19-46](https://user-images.githubusercontent.com/4975967/125940442-ada90919-e671-44d0-ba6d-39e85ac0fabd.png)

**Comment by metonym** [comment]
Firstly, wrap the TextInput and the first ComboBox with a `Column`

**Comment by ibilux** [comment]
> Firstly, wrap the TextInput and the first ComboBox with a `Column`

Thank you. That helped.

Any idea on how to set the length of the two columns of ComboBox & Button to 70% and 30%?

**Comment by metonym** [comment]
I would recommend using the `Column` props to control the widths of the columns. Keep in mind that the Carbon is grid is designed with specific portions in mind.

For example, try setting `xlg={11}` on one Column and `xlg={5}` on the other. This would be closest to 70/30. Or, you could try a 12/4 split.
