### ISSUE TITLE
hasIconOnly Button with anchor shows not-allowed cursor on hover

### ISSUE THREAD

**Issue by weaseldotro** [IBM/carbon-components-svelte#755]
Repl: https://svelte.dev/repl/f8e1432f50c243e8b6a21f235bb23b34
If you hover with the mouse over the button, the mouse cursor turns into a not-allowed icon. This is because the anchor element has a `disabled="false"` attribute. I'm guessing that the `disabled` attribute should not be present at all.

**Comment by metonym** [comment]
Fixed in v0.41.0
