### ISSUE TITLE
custom class name for components

### ISSUE THREAD

**Issue by basaran** [IBM/carbon-components-svelte#759]
Apologies for the simple question, but is there a way to assign custom classes to components? I'm trying to make a button 100% width.

#347 mentions some techniques, but I'm not sure if it is the same thing as what I'm trying to accomplish:

This doesn't work, with a friendly warning from vite `Unused CSS Selector`.

```
<Button icon={Add16} class="earth">Continue</Button>
```

If I inline the css, it works fine though:

```
<Button icon={Add16} style="width:100%">Continue</Button>
```

**Comment by basaran** [comment]
and as always, shortly after posting this, I discovered about the global option:

```
:global(.earth) {
        width: 100% !important;
    }
```

If you could please let me know if this is acceptable, would there be a better way?

**Comment by metonym** [comment]
That is a sensible approach. Another way would be to wrap components with a `div` to use Svelte's scoped styles. However, the downside is that it adds another more markup.

**Comment by basaran** [comment]
Thank you, closing.
