### ISSUE TITLE
svelte a11y warning "A11y: on:mouseover must be accompanied by on:focus" in version 3.39

### ISSUE THREAD

**Issue by metonym** [IBM/carbon-components-svelte#760]

**Comment by basaran** [comment]
I have this too.

**Comment by metonym** [comment]
Fixed by https://github.com/IBM/carbon-components-svelte/commit/a67e8a81f6dc5d7416ed6f4468efeb759593873c and released in [v0.42.1](https://github.com/IBM/carbon-components-svelte/releases/tag/v0.42.1)
