### ISSUE TITLE
ComboBox selectedIndex does not work correctly

### ISSUE THREAD

**Issue by sprnegr** [IBM/carbon-components-svelte#768]
After version 0.38.0 release `selectedIndex` on ComboBox component stopped working correctly - the selected value is not displayed until the focus event occurs for the ComboBox element.

I solve this problem returning [this line](https://github.com/IBM/carbon-components-svelte/compare/v0.37.0...v0.38.0#diff-3450feee793c0d5e0d3379e9987f16a04303de98f39f94416a5ea37f4daf9c31L152), but not sure that's right

**Comment by metonym** [comment]
Patched in v0.42.2
