### ISSUE TITLE
Add dropdown component

### ISSUE THREAD

**Issue by cal-smith** [IBM/carbon-components-svelte#9]
- [ ] single select dropdown
- [ ] multi-select dropdown

Considerations:
- dropdown list as a separate component (carbon-angular style)? Or dropdown types as separate components (carbon-react style)?
- dropdown items as array vs component?
- base `bx--listbox` components?
- take advantage of svelte binding and events ... `value` binding for selected items?

**Comment by metonym** [comment]
> dropdown items as array vs component?

IMO items should be a component (using set/getContext). For other "composed" components it should be children ideally (i.e. ContentSwitcher, Tabs).

However, maybe it would be a good idea to support both items as an array and as a component.

**Comment by cal-smith** [comment]
Yeah I'm leaning towards items as components overall, but there's definitely valid use cases for items as an array

**Comment by metonym** [comment]
The `TileGroup` + `RadioTile` components manage state through composition.

Parent-child communication is achieved through setContext/getContext API. A reactive value (i.e. current selected `RadioTile`) is set using the `svelte/store` API.

**[TileGroup (Parent)](https://github.com/IBM/carbon-components-svelte/blob/master/src/components/Tile/TileGroup.svelte#L15)**

```js
let tiles = [];
let selected = writable(defaultSelected);

setContext('TileGroup', {
  selected,
  addTile: tile => {
    tiles = [...tiles, tile];
  },
  updateSelected: tile => {
    selected.set(tile);
  }
});
```

**[RadioTile (child)](https://github.com/IBM/carbon-components-svelte/blob/master/src/components/Tile/RadioTile.svelte#L17)**

```js
const { addTile, updateSelected, selected } = getContext('TileGroup');

addTile({ id, value, checked });

$: checked = value === $selected.value;
```

**Comment by metonym** [comment]
Would you still be interested in this @cal-smith ?

After adding the [ComboBox component](https://github.com/IBM/carbon-components-svelte/blob/master/src/components/ComboBox/ComboBox.svelte), I strongly believe "items as components" (particularly for `Dropdown`, `ComboBox` etc.) would be a post-v1 feature.

For now, an `items` prop consisting of an array of objects where at least one field is mandatory (e.g. `{ text: string; }`) is sufficient. At least the text can be modifiable.

Additionally, the [ListBox](https://github.com/IBM/carbon-components-svelte/tree/master/src/components/ListBox) component has been created, which is shared between `ComboBox` and `MultiSelect` in addition to `Dropbox`.

**Comment by metonym** [comment]
Closed in https://github.com/IBM/carbon-components-svelte/commit/eb70437dc337dbaf37f3ab4ffc52014047ceced1
